name: JIMM Server Setup
description: "Create a JIMM environment"

inputs:
  jimm-version:
    description: >
      JIMM version tag to use. This will decide the version of JIMM to start e.g. v3.1.7
      A special tag of "dev" can be provided to use the current development version of JIMM.
    required: true
  juju-channel:
    description: 'Juju snap channel to pass to charmed-kubernetes/actions-operator'
    required: false
  ghcr-pat:
    description: >
      PAT Token that has package:read access to canonical/JIMM
      The PAT token can be left empty when building the development version of JIMM.
    required: true

outputs:
  url:
    description: 'URL where JIMM can be reached.'
    value: "https://jimm.localhost"
  client-id:
    description: 'Test client ID to login to JIMM with a service account.'
    value: "test-client-id"
  client-secret:
    description: 'Test client Secret to login to JIMM with a service account.'
    value: "2M2blFbO4GX4zfggQpivQSxwWX1XGgNf"
  ca-cert:
    description: 'The CA certificate used to genereate the JIMM server cert.'
    value: ${{ steps.fetch-cert.outputs.jimm-ca }}

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      if: ${{ inputs.jimm-version != 'dev' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.ghcr-pat }}

    # We can't use a make target here because a composite action
    # doesn't have a .git folder when checked out.
    - name: Start server based on released version
      if: ${{ inputs.jimm-version != 'dev' }}
      run: |
        cd local/traefik/certs; ./certs.sh; cd - && \
        docker compose --profile test up -d --wait
      shell: bash
      working-directory: ${{ github.action_path }}/../../..
      env:
        JIMM_VERSION: ${{ inputs.jimm-version }}

    - name: Start server based on development version
      if: ${{ inputs.jimm-version == 'dev' }}
      working-directory: ${{ github.action_path }}/../../..
      run: make dev-env
      shell: bash

    - name: Retrieve server CA cert.
      id: fetch-cert
      run: |
        echo 'jimm-ca<<EOF' >> $GITHUB_OUTPUT
        cat ./local/traefik/certs/ca.crt >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
      working-directory: ${{ github.action_path }}/../../..
      shell: bash

    - name: Initialise LXD
      run: |
        sudo lxd waitready && \
        sudo lxd init --auto && \
        sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket && \
        lxc network set lxdbr0 ipv6.address none && \
        sudo usermod -a -G lxd $USER
      shell: bash

    - name: Setup cloud-init script for bootstraping Juju controllers
      run: ./local/jimm/setup-controller.sh
      shell: bash
      working-directory: ${{ github.action_path }}/../../..
      env:
        SKIP_BOOTSTRAP: true
        CLOUDINIT_FILE: "cloudinit.temp.yaml"

    - name: Setup Juju Controller
      uses: charmed-kubernetes/actions-operator@main
      with:
        provider: "lxd"
        channel: "5.19/stable"
        juju-channel: ${{ inputs.juju-channel }}
        bootstrap-options: "--config ${{ github.action_path }}/../../../cloudinit.temp.yaml --config login-token-refresh-url=https://jimm.localhost/.well-known/jwks.json"

    # As described in https://github.com/charmed-kubernetes/actions-operator grab the newly setup controller name
    - name: Save LXD controller name
      id: lxd-controller
      run: echo "name=$CONTROLLER_NAME" >> $GITHUB_OUTPUT
      shell: bash

    - name: Install jimmctl, jaas plugin and yq
      run: |
        sudo snap install jimmctl --channel=3/stable && \
        sudo snap install jaas --channel=3/stable &&
        sudo snap install yq
      shell: bash

    - name: Authenticate Juju CLI
      run: chmod -R 666 ~/.local/share/juju/*.yaml && ./local/jimm/setup-cli-auth.sh
      working-directory: ${{ github.action_path }}/../../..
      shell: bash
      # Below is a hardcoded JWT using the same test-secret used in JIMM's docker compose and allows the CLI to authenticate as the jimm-test@canonical.com user.
      env:
        JWT: ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SnBjM01pT2lKUGJteHBibVVnU2xkVUlFSjFhV3hrWlhJaUxDSnBZWFFpT2pFM01qUXlNamcyTmpBc0ltVjRjQ0k2TXprMk5EYzFNelEyTUN3aVlYVmtJam9pYW1sdGJTSXNJbk4xWWlJNkltcHBiVzB0ZEdWemRFQmpZVzV2Ym1sallXd3VZMjl0SW4wLkpTWVhXcGF6T0FnX1VFZ2hkbjlOZkVQdWxhWWlJQVdaX3BuSmRDbnJvWEk=

    - name: Add LXD Juju controller to JIMM
      run: ./local/jimm/add-controller.sh
      working-directory: ${{ github.action_path }}/../../..
      shell: bash
      env:
        JIMM_CONTROLLER_NAME: "jimm"
        CONTROLLER_NAME: ${{ steps.lxd-controller.outputs.name }}

    - name: Provide service account with cloud-credentials
      run: ./local/jimm/setup-service-account.sh
      working-directory: ${{ github.action_path }}/../../..
      shell: bash
