version: "2"
run:
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: false
  allow-serial-runners: false
linters:
  default: none
  enable:
    - bodyclose
    - durationcheck
    - errcheck
    - gocognit
    - gocritic
    - goheader
    - gosec
    - govet
    - importas
    - ineffassign
    - nilerr
    - promlinter
    - reassign
    - sqlclosecheck
    - staticcheck
    - unused
  settings:
    gocognit:
      min-complexity: 30
    gosec:
      excludes:
        - G601
      severity: low
      confidence: low
    importas:
      alias:
        - pkg: github.com/juju/juju/rpc/params
          alias: jujuparams
        - pkg: github.com/canonical/jimm/v3/internal/openfga/names
          alias: ofganames
        - pkg: github.com/frankban/quicktest
          alias: qt
      no-unaliased: false
      no-extra-aliases: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  whole-files: false
  new: false
  fix: true
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
