name: jimm
version: git
summary: Juju Intelligent Model Manager
description: Multi-cloud controller for managing JAAS models.
grade: stable
confinement: strict

apps:
  jimm:
    command: jimm.wrapper
    daemon: simple
    plugs:
     - network
     - network-bind

parts:
  jimm:
    plugin: nil
    source: .
    source-type: git
    build-snaps:
     - go
    prime:
     - bin/jemd
    override-pull: |
      snapcraftctl pull
      go mod download
    override-build: |
      set -ex
      GIT_COMMIT=`git -C $SNAPCRAFT_PART_SRC rev-parse --verify HEAD`
      GIT_VERSION=`git -C $SNAPCRAFT_PART_SRC describe --dirty`
      cp version/init.go.tmpl version/init.go
      gofmt -w -r "unknownVersion -> Version{GitCommit: \"${GIT_COMMIT}\", Version: \"${GIT_VERSION}\",}" version/init.go
      GOBIN=${SNAPCRAFT_PART_INSTALL}/bin/ go install github.com/CanonicalLtd/jimm/cmd/jemd
  snapcraft:
    plugin: dump
    source: snapcraft
