// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/jujuclient2 (interfaces: ModelManagerClient,CloudClient,ApplicationOffersClient,ClientClient,ControllerClient,StorageClient,MiscClient,Dialer)
//
// Generated by this command:
//
//	mockgen -package mocks -destination ./internal/jujuclient2/mocks/clients.go ./internal/jujuclient2 ModelManagerClient,CloudClient,ApplicationOffersClient,ClientClient,ControllerClient,StorageClient,MiscClient,Dialer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	url "net/url"
	reflect "reflect"
	time "time"

	jujuclient2 "github.com/canonical/jimm/v3/internal/jujuclient2"
	api "github.com/juju/juju/api"
	base "github.com/juju/juju/api/base"
	client "github.com/juju/juju/api/client/client"
	cloud "github.com/juju/juju/api/client/cloud"
	controller "github.com/juju/juju/api/controller/controller"
	cloud0 "github.com/juju/juju/cloud"
	crossmodel "github.com/juju/juju/core/crossmodel"
	params "github.com/juju/juju/rpc/params"
	names "github.com/juju/names/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockModelManagerClient is a mock of ModelManagerClient interface.
type MockModelManagerClient struct {
	ctrl     *gomock.Controller
	recorder *MockModelManagerClientMockRecorder
	isgomock struct{}
}

// MockModelManagerClientMockRecorder is the mock recorder for MockModelManagerClient.
type MockModelManagerClientMockRecorder struct {
	mock *MockModelManagerClient
}

// NewMockModelManagerClient creates a new mock instance.
func NewMockModelManagerClient(ctrl *gomock.Controller) *MockModelManagerClient {
	mock := &MockModelManagerClient{ctrl: ctrl}
	mock.recorder = &MockModelManagerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelManagerClient) EXPECT() *MockModelManagerClientMockRecorder {
	return m.recorder
}

// ChangeModelCredential mocks base method.
func (m *MockModelManagerClient) ChangeModelCredential(model names.ModelTag, credential names.CloudCredentialTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeModelCredential", model, credential)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeModelCredential indicates an expected call of ChangeModelCredential.
func (mr *MockModelManagerClientMockRecorder) ChangeModelCredential(model, credential any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeModelCredential", reflect.TypeOf((*MockModelManagerClient)(nil).ChangeModelCredential), model, credential)
}

// Close mocks base method.
func (m *MockModelManagerClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockModelManagerClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockModelManagerClient)(nil).Close))
}

// CreateModel mocks base method.
func (m *MockModelManagerClient) CreateModel(name, owner, cloud, cloudRegion string, cloudCredential names.CloudCredentialTag, config map[string]any) (base.ModelInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModel", name, owner, cloud, cloudRegion, cloudCredential, config)
	ret0, _ := ret[0].(base.ModelInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModel indicates an expected call of CreateModel.
func (mr *MockModelManagerClientMockRecorder) CreateModel(name, owner, cloud, cloudRegion, cloudCredential, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModel", reflect.TypeOf((*MockModelManagerClient)(nil).CreateModel), name, owner, cloud, cloudRegion, cloudCredential, config)
}

// DestroyModel mocks base method.
func (m *MockModelManagerClient) DestroyModel(tag names.ModelTag, destroyStorage, force *bool, maxWait, timeout *time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyModel", tag, destroyStorage, force, maxWait, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyModel indicates an expected call of DestroyModel.
func (mr *MockModelManagerClientMockRecorder) DestroyModel(tag, destroyStorage, force, maxWait, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyModel", reflect.TypeOf((*MockModelManagerClient)(nil).DestroyModel), tag, destroyStorage, force, maxWait, timeout)
}

// DumpModel mocks base method.
func (m *MockModelManagerClient) DumpModel(model names.ModelTag, simplified bool) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DumpModel", model, simplified)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DumpModel indicates an expected call of DumpModel.
func (mr *MockModelManagerClientMockRecorder) DumpModel(model, simplified any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DumpModel", reflect.TypeOf((*MockModelManagerClient)(nil).DumpModel), model, simplified)
}

// DumpModelDB mocks base method.
func (m *MockModelManagerClient) DumpModelDB(model names.ModelTag) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DumpModelDB", model)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DumpModelDB indicates an expected call of DumpModelDB.
func (mr *MockModelManagerClientMockRecorder) DumpModelDB(model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DumpModelDB", reflect.TypeOf((*MockModelManagerClient)(nil).DumpModelDB), model)
}

// GrantModel mocks base method.
func (m *MockModelManagerClient) GrantModel(user, access string, modelUUIDs ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{user, access}
	for _, a := range modelUUIDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GrantModel", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// GrantModel indicates an expected call of GrantModel.
func (mr *MockModelManagerClientMockRecorder) GrantModel(user, access any, modelUUIDs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user, access}, modelUUIDs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantModel", reflect.TypeOf((*MockModelManagerClient)(nil).GrantModel), varargs...)
}

// ModelInfo mocks base method.
func (m *MockModelManagerClient) ModelInfo(tags []names.ModelTag) ([]params.ModelInfoResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelInfo", tags)
	ret0, _ := ret[0].([]params.ModelInfoResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelInfo indicates an expected call of ModelInfo.
func (mr *MockModelManagerClientMockRecorder) ModelInfo(tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelInfo", reflect.TypeOf((*MockModelManagerClient)(nil).ModelInfo), tags)
}

// ModelStatus mocks base method.
func (m *MockModelManagerClient) ModelStatus(tags ...names.ModelTag) ([]base.ModelStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range tags {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ModelStatus", varargs...)
	ret0, _ := ret[0].([]base.ModelStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelStatus indicates an expected call of ModelStatus.
func (mr *MockModelManagerClientMockRecorder) ModelStatus(tags ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelStatus", reflect.TypeOf((*MockModelManagerClient)(nil).ModelStatus), tags...)
}

// RevokeModel mocks base method.
func (m *MockModelManagerClient) RevokeModel(user, access string, modelUUIDs ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{user, access}
	for _, a := range modelUUIDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RevokeModel", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeModel indicates an expected call of RevokeModel.
func (mr *MockModelManagerClientMockRecorder) RevokeModel(user, access any, modelUUIDs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user, access}, modelUUIDs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeModel", reflect.TypeOf((*MockModelManagerClient)(nil).RevokeModel), varargs...)
}

// ValidateModelUpgrade mocks base method.
func (m *MockModelManagerClient) ValidateModelUpgrade(model names.ModelTag, force bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateModelUpgrade", model, force)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateModelUpgrade indicates an expected call of ValidateModelUpgrade.
func (mr *MockModelManagerClientMockRecorder) ValidateModelUpgrade(model, force any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateModelUpgrade", reflect.TypeOf((*MockModelManagerClient)(nil).ValidateModelUpgrade), model, force)
}

// MockCloudClient is a mock of CloudClient interface.
type MockCloudClient struct {
	ctrl     *gomock.Controller
	recorder *MockCloudClientMockRecorder
	isgomock struct{}
}

// MockCloudClientMockRecorder is the mock recorder for MockCloudClient.
type MockCloudClientMockRecorder struct {
	mock *MockCloudClient
}

// NewMockCloudClient creates a new mock instance.
func NewMockCloudClient(ctrl *gomock.Controller) *MockCloudClient {
	mock := &MockCloudClient{ctrl: ctrl}
	mock.recorder = &MockCloudClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudClient) EXPECT() *MockCloudClientMockRecorder {
	return m.recorder
}

// AddCloud mocks base method.
func (m *MockCloudClient) AddCloud(cloud cloud0.Cloud, force bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCloud", cloud, force)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCloud indicates an expected call of AddCloud.
func (mr *MockCloudClientMockRecorder) AddCloud(cloud, force any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCloud", reflect.TypeOf((*MockCloudClient)(nil).AddCloud), cloud, force)
}

// Close mocks base method.
func (m *MockCloudClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCloudClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCloudClient)(nil).Close))
}

// Cloud mocks base method.
func (m *MockCloudClient) Cloud(tag names.CloudTag) (cloud0.Cloud, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cloud", tag)
	ret0, _ := ret[0].(cloud0.Cloud)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cloud indicates an expected call of Cloud.
func (mr *MockCloudClientMockRecorder) Cloud(tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cloud", reflect.TypeOf((*MockCloudClient)(nil).Cloud), tag)
}

// CloudInfo mocks base method.
func (m *MockCloudClient) CloudInfo(tags []names.CloudTag) ([]cloud.CloudInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloudInfo", tags)
	ret0, _ := ret[0].([]cloud.CloudInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloudInfo indicates an expected call of CloudInfo.
func (mr *MockCloudClientMockRecorder) CloudInfo(tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloudInfo", reflect.TypeOf((*MockCloudClient)(nil).CloudInfo), tags)
}

// Clouds mocks base method.
func (m *MockCloudClient) Clouds() (map[names.CloudTag]cloud0.Cloud, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clouds")
	ret0, _ := ret[0].(map[names.CloudTag]cloud0.Cloud)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clouds indicates an expected call of Clouds.
func (mr *MockCloudClientMockRecorder) Clouds() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clouds", reflect.TypeOf((*MockCloudClient)(nil).Clouds))
}

// GrantCloud mocks base method.
func (m *MockCloudClient) GrantCloud(user, access string, clouds ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{user, access}
	for _, a := range clouds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GrantCloud", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// GrantCloud indicates an expected call of GrantCloud.
func (mr *MockCloudClientMockRecorder) GrantCloud(user, access any, clouds ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user, access}, clouds...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantCloud", reflect.TypeOf((*MockCloudClient)(nil).GrantCloud), varargs...)
}

// RemoveCloud mocks base method.
func (m *MockCloudClient) RemoveCloud(cloud string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCloud", cloud)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCloud indicates an expected call of RemoveCloud.
func (mr *MockCloudClientMockRecorder) RemoveCloud(cloud any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCloud", reflect.TypeOf((*MockCloudClient)(nil).RemoveCloud), cloud)
}

// RevokeCloud mocks base method.
func (m *MockCloudClient) RevokeCloud(user, access string, clouds ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{user, access}
	for _, a := range clouds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RevokeCloud", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeCloud indicates an expected call of RevokeCloud.
func (mr *MockCloudClientMockRecorder) RevokeCloud(user, access any, clouds ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user, access}, clouds...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeCloud", reflect.TypeOf((*MockCloudClient)(nil).RevokeCloud), varargs...)
}

// RevokeCredential mocks base method.
func (m *MockCloudClient) RevokeCredential(tag names.CloudCredentialTag, force bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeCredential", tag, force)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeCredential indicates an expected call of RevokeCredential.
func (mr *MockCloudClientMockRecorder) RevokeCredential(tag, force any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeCredential", reflect.TypeOf((*MockCloudClient)(nil).RevokeCredential), tag, force)
}

// UpdateCloud mocks base method.
func (m *MockCloudClient) UpdateCloud(cloud cloud0.Cloud) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCloud", cloud)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCloud indicates an expected call of UpdateCloud.
func (mr *MockCloudClientMockRecorder) UpdateCloud(cloud any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCloud", reflect.TypeOf((*MockCloudClient)(nil).UpdateCloud), cloud)
}

// MockApplicationOffersClient is a mock of ApplicationOffersClient interface.
type MockApplicationOffersClient struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationOffersClientMockRecorder
	isgomock struct{}
}

// MockApplicationOffersClientMockRecorder is the mock recorder for MockApplicationOffersClient.
type MockApplicationOffersClientMockRecorder struct {
	mock *MockApplicationOffersClient
}

// NewMockApplicationOffersClient creates a new mock instance.
func NewMockApplicationOffersClient(ctrl *gomock.Controller) *MockApplicationOffersClient {
	mock := &MockApplicationOffersClient{ctrl: ctrl}
	mock.recorder = &MockApplicationOffersClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationOffersClient) EXPECT() *MockApplicationOffersClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockApplicationOffersClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockApplicationOffersClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockApplicationOffersClient)(nil).Close))
}

// DestroyOffers mocks base method.
func (m *MockApplicationOffersClient) DestroyOffers(force bool, offerURLs ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{force}
	for _, a := range offerURLs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DestroyOffers", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyOffers indicates an expected call of DestroyOffers.
func (mr *MockApplicationOffersClientMockRecorder) DestroyOffers(force any, offerURLs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{force}, offerURLs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyOffers", reflect.TypeOf((*MockApplicationOffersClient)(nil).DestroyOffers), varargs...)
}

// FindApplicationOffers mocks base method.
func (m *MockApplicationOffersClient) FindApplicationOffers(filters ...crossmodel.ApplicationOfferFilter) ([]*crossmodel.ApplicationOfferDetails, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range filters {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindApplicationOffers", varargs...)
	ret0, _ := ret[0].([]*crossmodel.ApplicationOfferDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindApplicationOffers indicates an expected call of FindApplicationOffers.
func (mr *MockApplicationOffersClientMockRecorder) FindApplicationOffers(filters ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindApplicationOffers", reflect.TypeOf((*MockApplicationOffersClient)(nil).FindApplicationOffers), filters...)
}

// GetConsumeDetails mocks base method.
func (m *MockApplicationOffersClient) GetConsumeDetails(urlStr string) (params.ConsumeOfferDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsumeDetails", urlStr)
	ret0, _ := ret[0].(params.ConsumeOfferDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsumeDetails indicates an expected call of GetConsumeDetails.
func (mr *MockApplicationOffersClientMockRecorder) GetConsumeDetails(urlStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsumeDetails", reflect.TypeOf((*MockApplicationOffersClient)(nil).GetConsumeDetails), urlStr)
}

// GrantOffer mocks base method.
func (m *MockApplicationOffersClient) GrantOffer(user, access string, offerURLs ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{user, access}
	for _, a := range offerURLs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GrantOffer", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// GrantOffer indicates an expected call of GrantOffer.
func (mr *MockApplicationOffersClientMockRecorder) GrantOffer(user, access any, offerURLs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user, access}, offerURLs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantOffer", reflect.TypeOf((*MockApplicationOffersClient)(nil).GrantOffer), varargs...)
}

// ListOffers mocks base method.
func (m *MockApplicationOffersClient) ListOffers(filters ...crossmodel.ApplicationOfferFilter) ([]*crossmodel.ApplicationOfferDetails, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range filters {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListOffers", varargs...)
	ret0, _ := ret[0].([]*crossmodel.ApplicationOfferDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOffers indicates an expected call of ListOffers.
func (mr *MockApplicationOffersClientMockRecorder) ListOffers(filters ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOffers", reflect.TypeOf((*MockApplicationOffersClient)(nil).ListOffers), filters...)
}

// Offer mocks base method.
func (m *MockApplicationOffersClient) Offer(modelUUID, application string, endpoints []string, owner, offerName, desc string) ([]params.ErrorResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Offer", modelUUID, application, endpoints, owner, offerName, desc)
	ret0, _ := ret[0].([]params.ErrorResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Offer indicates an expected call of Offer.
func (mr *MockApplicationOffersClientMockRecorder) Offer(modelUUID, application, endpoints, owner, offerName, desc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Offer", reflect.TypeOf((*MockApplicationOffersClient)(nil).Offer), modelUUID, application, endpoints, owner, offerName, desc)
}

// RevokeOffer mocks base method.
func (m *MockApplicationOffersClient) RevokeOffer(user, access string, offerURLs ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{user, access}
	for _, a := range offerURLs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RevokeOffer", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeOffer indicates an expected call of RevokeOffer.
func (mr *MockApplicationOffersClientMockRecorder) RevokeOffer(user, access any, offerURLs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{user, access}, offerURLs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeOffer", reflect.TypeOf((*MockApplicationOffersClient)(nil).RevokeOffer), varargs...)
}

// MockClientClient is a mock of ClientClient interface.
type MockClientClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientClientMockRecorder
	isgomock struct{}
}

// MockClientClientMockRecorder is the mock recorder for MockClientClient.
type MockClientClientMockRecorder struct {
	mock *MockClientClient
}

// NewMockClientClient creates a new mock instance.
func NewMockClientClient(ctrl *gomock.Controller) *MockClientClient {
	mock := &MockClientClient{ctrl: ctrl}
	mock.recorder = &MockClientClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientClient) EXPECT() *MockClientClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClientClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClientClient)(nil).Close))
}

// Status mocks base method.
func (m *MockClientClient) Status(args *client.StatusArgs) (*params.FullStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", args)
	ret0, _ := ret[0].(*params.FullStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockClientClientMockRecorder) Status(args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockClientClient)(nil).Status), args)
}

// MockControllerClient is a mock of ControllerClient interface.
type MockControllerClient struct {
	ctrl     *gomock.Controller
	recorder *MockControllerClientMockRecorder
	isgomock struct{}
}

// MockControllerClientMockRecorder is the mock recorder for MockControllerClient.
type MockControllerClientMockRecorder struct {
	mock *MockControllerClient
}

// NewMockControllerClient creates a new mock instance.
func NewMockControllerClient(ctrl *gomock.Controller) *MockControllerClient {
	mock := &MockControllerClient{ctrl: ctrl}
	mock.recorder = &MockControllerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControllerClient) EXPECT() *MockControllerClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockControllerClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockControllerClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockControllerClient)(nil).Close))
}

// WatchAllModelSummaries mocks base method.
func (m *MockControllerClient) WatchAllModelSummaries() (*controller.SummaryWatcher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchAllModelSummaries")
	ret0, _ := ret[0].(*controller.SummaryWatcher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchAllModelSummaries indicates an expected call of WatchAllModelSummaries.
func (mr *MockControllerClientMockRecorder) WatchAllModelSummaries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchAllModelSummaries", reflect.TypeOf((*MockControllerClient)(nil).WatchAllModelSummaries))
}

// WatchAllModels mocks base method.
func (m *MockControllerClient) WatchAllModels() (*api.AllWatcher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchAllModels")
	ret0, _ := ret[0].(*api.AllWatcher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchAllModels indicates an expected call of WatchAllModels.
func (mr *MockControllerClientMockRecorder) WatchAllModels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchAllModels", reflect.TypeOf((*MockControllerClient)(nil).WatchAllModels))
}

// WatchModelSummaries mocks base method.
func (m *MockControllerClient) WatchModelSummaries() (*controller.SummaryWatcher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchModelSummaries")
	ret0, _ := ret[0].(*controller.SummaryWatcher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchModelSummaries indicates an expected call of WatchModelSummaries.
func (mr *MockControllerClientMockRecorder) WatchModelSummaries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchModelSummaries", reflect.TypeOf((*MockControllerClient)(nil).WatchModelSummaries))
}

// MockStorageClient is a mock of StorageClient interface.
type MockStorageClient struct {
	ctrl     *gomock.Controller
	recorder *MockStorageClientMockRecorder
	isgomock struct{}
}

// MockStorageClientMockRecorder is the mock recorder for MockStorageClient.
type MockStorageClientMockRecorder struct {
	mock *MockStorageClient
}

// NewMockStorageClient creates a new mock instance.
func NewMockStorageClient(ctrl *gomock.Controller) *MockStorageClient {
	mock := &MockStorageClient{ctrl: ctrl}
	mock.recorder = &MockStorageClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageClient) EXPECT() *MockStorageClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStorageClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStorageClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorageClient)(nil).Close))
}

// ListFilesystems mocks base method.
func (m *MockStorageClient) ListFilesystems(machines []string) ([]params.FilesystemDetailsListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFilesystems", machines)
	ret0, _ := ret[0].([]params.FilesystemDetailsListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFilesystems indicates an expected call of ListFilesystems.
func (mr *MockStorageClientMockRecorder) ListFilesystems(machines any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFilesystems", reflect.TypeOf((*MockStorageClient)(nil).ListFilesystems), machines)
}

// ListStorageDetails mocks base method.
func (m *MockStorageClient) ListStorageDetails() ([]params.StorageDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStorageDetails")
	ret0, _ := ret[0].([]params.StorageDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStorageDetails indicates an expected call of ListStorageDetails.
func (mr *MockStorageClientMockRecorder) ListStorageDetails() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStorageDetails", reflect.TypeOf((*MockStorageClient)(nil).ListStorageDetails))
}

// ListVolumes mocks base method.
func (m *MockStorageClient) ListVolumes(machines []string) ([]params.VolumeDetailsListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVolumes", machines)
	ret0, _ := ret[0].([]params.VolumeDetailsListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVolumes indicates an expected call of ListVolumes.
func (mr *MockStorageClientMockRecorder) ListVolumes(machines any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVolumes", reflect.TypeOf((*MockStorageClient)(nil).ListVolumes), machines)
}

// MockMiscClient is a mock of MiscClient interface.
type MockMiscClient struct {
	ctrl     *gomock.Controller
	recorder *MockMiscClientMockRecorder
	isgomock struct{}
}

// MockMiscClientMockRecorder is the mock recorder for MockMiscClient.
type MockMiscClientMockRecorder struct {
	mock *MockMiscClient
}

// NewMockMiscClient creates a new mock instance.
func NewMockMiscClient(ctrl *gomock.Controller) *MockMiscClient {
	mock := &MockMiscClient{ctrl: ctrl}
	mock.recorder = &MockMiscClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiscClient) EXPECT() *MockMiscClientMockRecorder {
	return m.recorder
}

// CheckCredentialModels mocks base method.
func (m *MockMiscClient) CheckCredentialModels(arg0 context.Context, arg1 params.TaggedCredential) ([]params.UpdateCredentialModelResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCredentialModels", arg0, arg1)
	ret0, _ := ret[0].([]params.UpdateCredentialModelResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCredentialModels indicates an expected call of CheckCredentialModels.
func (mr *MockMiscClientMockRecorder) CheckCredentialModels(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCredentialModels", reflect.TypeOf((*MockMiscClient)(nil).CheckCredentialModels), arg0, arg1)
}

// Close mocks base method.
func (m *MockMiscClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMiscClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMiscClient)(nil).Close))
}

// ConnectStream mocks base method.
func (m *MockMiscClient) ConnectStream(arg0 string, arg1 url.Values) (base.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectStream", arg0, arg1)
	ret0, _ := ret[0].(base.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConnectStream indicates an expected call of ConnectStream.
func (mr *MockMiscClientMockRecorder) ConnectStream(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectStream", reflect.TypeOf((*MockMiscClient)(nil).ConnectStream), arg0, arg1)
}

// ControllerModelSummary mocks base method.
func (m *MockMiscClient) ControllerModelSummary(arg0 context.Context, arg1 *params.ModelSummary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ControllerModelSummary", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ControllerModelSummary indicates an expected call of ControllerModelSummary.
func (mr *MockMiscClientMockRecorder) ControllerModelSummary(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ControllerModelSummary", reflect.TypeOf((*MockMiscClient)(nil).ControllerModelSummary), arg0, arg1)
}

// GetApplicationOffer mocks base method.
func (m *MockMiscClient) GetApplicationOffer(arg0 context.Context, arg1 *params.ApplicationOfferAdminDetailsV5) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApplicationOffer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetApplicationOffer indicates an expected call of GetApplicationOffer.
func (mr *MockMiscClientMockRecorder) GetApplicationOffer(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApplicationOffer", reflect.TypeOf((*MockMiscClient)(nil).GetApplicationOffer), arg0, arg1)
}

// GrantJIMMModelAdmin mocks base method.
func (m *MockMiscClient) GrantJIMMModelAdmin(arg0 context.Context, arg1 names.ModelTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantJIMMModelAdmin", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GrantJIMMModelAdmin indicates an expected call of GrantJIMMModelAdmin.
func (mr *MockMiscClientMockRecorder) GrantJIMMModelAdmin(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantJIMMModelAdmin", reflect.TypeOf((*MockMiscClient)(nil).GrantJIMMModelAdmin), arg0, arg1)
}

// UpdateCredential mocks base method.
func (m *MockMiscClient) UpdateCredential(arg0 context.Context, arg1 params.TaggedCredential) ([]params.UpdateCredentialModelResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCredential", arg0, arg1)
	ret0, _ := ret[0].([]params.UpdateCredentialModelResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCredential indicates an expected call of UpdateCredential.
func (mr *MockMiscClientMockRecorder) UpdateCredential(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCredential", reflect.TypeOf((*MockMiscClient)(nil).UpdateCredential), arg0, arg1)
}

// WatchAll mocks base method.
func (m *MockMiscClient) WatchAll(arg0 context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchAll", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchAll indicates an expected call of WatchAll.
func (mr *MockMiscClientMockRecorder) WatchAll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchAll", reflect.TypeOf((*MockMiscClient)(nil).WatchAll), arg0)
}

// MockDialer is a mock of Dialer interface.
type MockDialer struct {
	ctrl     *gomock.Controller
	recorder *MockDialerMockRecorder
	isgomock struct{}
}

// MockDialerMockRecorder is the mock recorder for MockDialer.
type MockDialerMockRecorder struct {
	mock *MockDialer
}

// NewMockDialer creates a new mock instance.
func NewMockDialer(ctrl *gomock.Controller) *MockDialer {
	mock := &MockDialer{ctrl: ctrl}
	mock.recorder = &MockDialerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDialer) EXPECT() *MockDialerMockRecorder {
	return m.recorder
}

// Dial mocks base method.
func (m *MockDialer) Dial(arg0 jujuclient2.DialParams) (api.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dial", arg0)
	ret0, _ := ret[0].(api.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dial indicates an expected call of Dial.
func (mr *MockDialerMockRecorder) Dial(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dial", reflect.TypeOf((*MockDialer)(nil).Dial), arg0)
}
