#!/usr/bin/env python3

import os
import uuid

import yaml


src = os.path.join(os.getenv('SNAP'), 'etc', 'jimm', 'config.yaml')
dst = os.path.join(os.getenv('SNAP_DATA'), 'config.yaml')

with open(src) as f:
    cfg = yaml.safe_load(f)
cfg['controller-uuid'] = str(uuid.uuid4())
with open(dst, 'w') as f:
    yaml.safe_dump(cfg, f)
