// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/cmd/jaas/cmd (interfaces: JIMMAPI)
//
// Generated by this command:
//
//	mockgen -package mocks -typed -destination ./mocks/client_mock.go github.com/canonical/jimm/v3/cmd/jaas/cmd JIMMAPI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	params "github.com/canonical/jimm/v3/pkg/api/params"
	gomock "go.uber.org/mock/gomock"
)

// MockJIMMAPI is a mock of JIMMAPI interface.
type MockJIMMAPI struct {
	ctrl     *gomock.Controller
	recorder *MockJIMMAPIMockRecorder
	isgomock struct{}
}

// MockJIMMAPIMockRecorder is the mock recorder for MockJIMMAPI.
type MockJIMMAPIMockRecorder struct {
	mock *MockJIMMAPI
}

// NewMockJIMMAPI creates a new mock instance.
func NewMockJIMMAPI(ctrl *gomock.Controller) *MockJIMMAPI {
	mock := &MockJIMMAPI{ctrl: ctrl}
	mock.recorder = &MockJIMMAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJIMMAPI) EXPECT() *MockJIMMAPIMockRecorder {
	return m.recorder
}

// Bootstrap mocks base method.
func (m *MockJIMMAPI) Bootstrap(req *params.BootstrapStartParams) (*params.BootstrapStartResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bootstrap", req)
	ret0, _ := ret[0].(*params.BootstrapStartResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Bootstrap indicates an expected call of Bootstrap.
func (mr *MockJIMMAPIMockRecorder) Bootstrap(req any) *MockJIMMAPIBootstrapCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bootstrap", reflect.TypeOf((*MockJIMMAPI)(nil).Bootstrap), req)
	return &MockJIMMAPIBootstrapCall{Call: call}
}

// MockJIMMAPIBootstrapCall wrap *gomock.Call
type MockJIMMAPIBootstrapCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJIMMAPIBootstrapCall) Return(arg0 *params.BootstrapStartResponse, arg1 error) *MockJIMMAPIBootstrapCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJIMMAPIBootstrapCall) Do(f func(*params.BootstrapStartParams) (*params.BootstrapStartResponse, error)) *MockJIMMAPIBootstrapCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJIMMAPIBootstrapCall) DoAndReturn(f func(*params.BootstrapStartParams) (*params.BootstrapStartResponse, error)) *MockJIMMAPIBootstrapCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BootstrapStatus mocks base method.
func (m *MockJIMMAPI) BootstrapStatus(req *params.BootstrapStatusRequest) (params.BootstrapStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BootstrapStatus", req)
	ret0, _ := ret[0].(params.BootstrapStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BootstrapStatus indicates an expected call of BootstrapStatus.
func (mr *MockJIMMAPIMockRecorder) BootstrapStatus(req any) *MockJIMMAPIBootstrapStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BootstrapStatus", reflect.TypeOf((*MockJIMMAPI)(nil).BootstrapStatus), req)
	return &MockJIMMAPIBootstrapStatusCall{Call: call}
}

// MockJIMMAPIBootstrapStatusCall wrap *gomock.Call
type MockJIMMAPIBootstrapStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJIMMAPIBootstrapStatusCall) Return(arg0 params.BootstrapStatusResponse, arg1 error) *MockJIMMAPIBootstrapStatusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJIMMAPIBootstrapStatusCall) Do(f func(*params.BootstrapStatusRequest) (params.BootstrapStatusResponse, error)) *MockJIMMAPIBootstrapStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJIMMAPIBootstrapStatusCall) DoAndReturn(f func(*params.BootstrapStatusRequest) (params.BootstrapStatusResponse, error)) *MockJIMMAPIBootstrapStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BootstrapStop mocks base method.
func (m *MockJIMMAPI) BootstrapStop(req *params.BootstrapStopRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BootstrapStop", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// BootstrapStop indicates an expected call of BootstrapStop.
func (mr *MockJIMMAPIMockRecorder) BootstrapStop(req any) *MockJIMMAPIBootstrapStopCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BootstrapStop", reflect.TypeOf((*MockJIMMAPI)(nil).BootstrapStop), req)
	return &MockJIMMAPIBootstrapStopCall{Call: call}
}

// MockJIMMAPIBootstrapStopCall wrap *gomock.Call
type MockJIMMAPIBootstrapStopCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJIMMAPIBootstrapStopCall) Return(arg0 error) *MockJIMMAPIBootstrapStopCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJIMMAPIBootstrapStopCall) Do(f func(*params.BootstrapStopRequest) error) *MockJIMMAPIBootstrapStopCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJIMMAPIBootstrapStopCall) DoAndReturn(f func(*params.BootstrapStopRequest) error) *MockJIMMAPIBootstrapStopCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Close mocks base method.
func (m *MockJIMMAPI) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockJIMMAPIMockRecorder) Close() *MockJIMMAPICloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockJIMMAPI)(nil).Close))
	return &MockJIMMAPICloseCall{Call: call}
}

// MockJIMMAPICloseCall wrap *gomock.Call
type MockJIMMAPICloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJIMMAPICloseCall) Return(arg0 error) *MockJIMMAPICloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJIMMAPICloseCall) Do(f func() error) *MockJIMMAPICloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJIMMAPICloseCall) DoAndReturn(f func() error) *MockJIMMAPICloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListMigrationTargets mocks base method.
func (m *MockJIMMAPI) ListMigrationTargets(req *params.ListMigrationTargetsRequest) ([]params.ControllerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMigrationTargets", req)
	ret0, _ := ret[0].([]params.ControllerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMigrationTargets indicates an expected call of ListMigrationTargets.
func (mr *MockJIMMAPIMockRecorder) ListMigrationTargets(req any) *MockJIMMAPIListMigrationTargetsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMigrationTargets", reflect.TypeOf((*MockJIMMAPI)(nil).ListMigrationTargets), req)
	return &MockJIMMAPIListMigrationTargetsCall{Call: call}
}

// MockJIMMAPIListMigrationTargetsCall wrap *gomock.Call
type MockJIMMAPIListMigrationTargetsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJIMMAPIListMigrationTargetsCall) Return(arg0 []params.ControllerInfo, arg1 error) *MockJIMMAPIListMigrationTargetsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJIMMAPIListMigrationTargetsCall) Do(f func(*params.ListMigrationTargetsRequest) ([]params.ControllerInfo, error)) *MockJIMMAPIListMigrationTargetsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJIMMAPIListMigrationTargetsCall) DoAndReturn(f func(*params.ListMigrationTargetsRequest) ([]params.ControllerInfo, error)) *MockJIMMAPIListMigrationTargetsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PrepareModelMigration mocks base method.
func (m *MockJIMMAPI) PrepareModelMigration(req *params.PrepareModelMigrationRequest) (params.PrepareModelMigrationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareModelMigration", req)
	ret0, _ := ret[0].(params.PrepareModelMigrationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareModelMigration indicates an expected call of PrepareModelMigration.
func (mr *MockJIMMAPIMockRecorder) PrepareModelMigration(req any) *MockJIMMAPIPrepareModelMigrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareModelMigration", reflect.TypeOf((*MockJIMMAPI)(nil).PrepareModelMigration), req)
	return &MockJIMMAPIPrepareModelMigrationCall{Call: call}
}

// MockJIMMAPIPrepareModelMigrationCall wrap *gomock.Call
type MockJIMMAPIPrepareModelMigrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJIMMAPIPrepareModelMigrationCall) Return(arg0 params.PrepareModelMigrationResponse, arg1 error) *MockJIMMAPIPrepareModelMigrationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJIMMAPIPrepareModelMigrationCall) Do(f func(*params.PrepareModelMigrationRequest) (params.PrepareModelMigrationResponse, error)) *MockJIMMAPIPrepareModelMigrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJIMMAPIPrepareModelMigrationCall) DoAndReturn(f func(*params.PrepareModelMigrationRequest) (params.PrepareModelMigrationResponse, error)) *MockJIMMAPIPrepareModelMigrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
