// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/cmd/jaas/cmd (interfaces: JIMMClient)
//
// Generated by this command:
//
//	mockgen -package mocks -typed -destination ./mocks/client_mock.go github.com/canonical/jimm/v3/cmd/jaas/cmd JIMMClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	params "github.com/canonical/jimm/v3/pkg/api/params"
	gomock "go.uber.org/mock/gomock"
)

// MockJIMMClient is a mock of JIMMClient interface.
type MockJIMMClient struct {
	ctrl     *gomock.Controller
	recorder *MockJIMMClientMockRecorder
	isgomock struct{}
}

// MockJIMMClientMockRecorder is the mock recorder for MockJIMMClient.
type MockJIMMClientMockRecorder struct {
	mock *MockJIMMClient
}

// NewMockJIMMClient creates a new mock instance.
func NewMockJIMMClient(ctrl *gomock.Controller) *MockJIMMClient {
	mock := &MockJIMMClient{ctrl: ctrl}
	mock.recorder = &MockJIMMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJIMMClient) EXPECT() *MockJIMMClientMockRecorder {
	return m.recorder
}

// BootstrapStatus mocks base method.
func (m *MockJIMMClient) BootstrapStatus(req *params.BootstrapStatusRequest) (params.BootstrapStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BootstrapStatus", req)
	ret0, _ := ret[0].(params.BootstrapStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BootstrapStatus indicates an expected call of BootstrapStatus.
func (mr *MockJIMMClientMockRecorder) BootstrapStatus(req any) *MockJIMMClientBootstrapStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BootstrapStatus", reflect.TypeOf((*MockJIMMClient)(nil).BootstrapStatus), req)
	return &MockJIMMClientBootstrapStatusCall{Call: call}
}

// MockJIMMClientBootstrapStatusCall wrap *gomock.Call
type MockJIMMClientBootstrapStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJIMMClientBootstrapStatusCall) Return(arg0 params.BootstrapStatusResponse, arg1 error) *MockJIMMClientBootstrapStatusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJIMMClientBootstrapStatusCall) Do(f func(*params.BootstrapStatusRequest) (params.BootstrapStatusResponse, error)) *MockJIMMClientBootstrapStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJIMMClientBootstrapStatusCall) DoAndReturn(f func(*params.BootstrapStatusRequest) (params.BootstrapStatusResponse, error)) *MockJIMMClientBootstrapStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
