// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/cmd/jaas/cmd (interfaces: MigrateAPI)
//
// Generated by this command:
//
//	mockgen -package mocks -typed -destination ./mocks/migrate_mock.go github.com/canonical/jimm/v3/cmd/jaas/cmd MigrateAPI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	controller "github.com/juju/juju/api/controller/controller"
	crossmodel "github.com/juju/juju/core/crossmodel"
	params "github.com/juju/juju/rpc/params"
	names "github.com/juju/names/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockMigrateAPI is a mock of MigrateAPI interface.
type MockMigrateAPI struct {
	ctrl     *gomock.Controller
	recorder *MockMigrateAPIMockRecorder
	isgomock struct{}
}

// MockMigrateAPIMockRecorder is the mock recorder for MockMigrateAPI.
type MockMigrateAPIMockRecorder struct {
	mock *MockMigrateAPI
}

// NewMockMigrateAPI creates a new mock instance.
func NewMockMigrateAPI(ctrl *gomock.Controller) *MockMigrateAPI {
	mock := &MockMigrateAPI{ctrl: ctrl}
	mock.recorder = &MockMigrateAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMigrateAPI) EXPECT() *MockMigrateAPIMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMigrateAPI) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMigrateAPIMockRecorder) Close() *MockMigrateAPICloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMigrateAPI)(nil).Close))
	return &MockMigrateAPICloseCall{Call: call}
}

// MockMigrateAPICloseCall wrap *gomock.Call
type MockMigrateAPICloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMigrateAPICloseCall) Return(arg0 error) *MockMigrateAPICloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMigrateAPICloseCall) Do(f func() error) *MockMigrateAPICloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMigrateAPICloseCall) DoAndReturn(f func() error) *MockMigrateAPICloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InitiateMigration mocks base method.
func (m *MockMigrateAPI) InitiateMigration(spec controller.MigrationSpec) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateMigration", spec)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateMigration indicates an expected call of InitiateMigration.
func (mr *MockMigrateAPIMockRecorder) InitiateMigration(spec any) *MockMigrateAPIInitiateMigrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateMigration", reflect.TypeOf((*MockMigrateAPI)(nil).InitiateMigration), spec)
	return &MockMigrateAPIInitiateMigrationCall{Call: call}
}

// MockMigrateAPIInitiateMigrationCall wrap *gomock.Call
type MockMigrateAPIInitiateMigrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMigrateAPIInitiateMigrationCall) Return(arg0 string, arg1 error) *MockMigrateAPIInitiateMigrationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMigrateAPIInitiateMigrationCall) Do(f func(controller.MigrationSpec) (string, error)) *MockMigrateAPIInitiateMigrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMigrateAPIInitiateMigrationCall) DoAndReturn(f func(controller.MigrationSpec) (string, error)) *MockMigrateAPIInitiateMigrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListOffers mocks base method.
func (m *MockMigrateAPI) ListOffers(filters ...crossmodel.ApplicationOfferFilter) ([]*crossmodel.ApplicationOfferDetails, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range filters {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListOffers", varargs...)
	ret0, _ := ret[0].([]*crossmodel.ApplicationOfferDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOffers indicates an expected call of ListOffers.
func (mr *MockMigrateAPIMockRecorder) ListOffers(filters ...any) *MockMigrateAPIListOffersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOffers", reflect.TypeOf((*MockMigrateAPI)(nil).ListOffers), filters...)
	return &MockMigrateAPIListOffersCall{Call: call}
}

// MockMigrateAPIListOffersCall wrap *gomock.Call
type MockMigrateAPIListOffersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMigrateAPIListOffersCall) Return(arg0 []*crossmodel.ApplicationOfferDetails, arg1 error) *MockMigrateAPIListOffersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMigrateAPIListOffersCall) Do(f func(...crossmodel.ApplicationOfferFilter) ([]*crossmodel.ApplicationOfferDetails, error)) *MockMigrateAPIListOffersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMigrateAPIListOffersCall) DoAndReturn(f func(...crossmodel.ApplicationOfferFilter) ([]*crossmodel.ApplicationOfferDetails, error)) *MockMigrateAPIListOffersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ModelInfo mocks base method.
func (m *MockMigrateAPI) ModelInfo(tags []names.ModelTag) ([]params.ModelInfoResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelInfo", tags)
	ret0, _ := ret[0].([]params.ModelInfoResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelInfo indicates an expected call of ModelInfo.
func (mr *MockMigrateAPIMockRecorder) ModelInfo(tags any) *MockMigrateAPIModelInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelInfo", reflect.TypeOf((*MockMigrateAPI)(nil).ModelInfo), tags)
	return &MockMigrateAPIModelInfoCall{Call: call}
}

// MockMigrateAPIModelInfoCall wrap *gomock.Call
type MockMigrateAPIModelInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMigrateAPIModelInfoCall) Return(arg0 []params.ModelInfoResult, arg1 error) *MockMigrateAPIModelInfoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMigrateAPIModelInfoCall) Do(f func([]names.ModelTag) ([]params.ModelInfoResult, error)) *MockMigrateAPIModelInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMigrateAPIModelInfoCall) DoAndReturn(f func([]names.ModelTag) ([]params.ModelInfoResult, error)) *MockMigrateAPIModelInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
