#!/usr/bin/python3

from charmhelpers.core import hookenv
import jaascharm
from status import charm_status


def update_status():
    status, _ = hookenv.status_get()
    if status == 'waiting' or status == 'blocked':
        return
    jaascharm.update_status(failed_status=charm_status)


if __name__ == '__main__':
    hookenv.log('update-status')
    update_status()
