name: jaas
summary: JAAS plugin
description: Juju plugin for providing JAAS functionality to the Juju CLI.
version: git
grade: stable
base: bare
build-base: core20
confinement: strict

slots:
  jaas-plugin:
    interface: content
    content: jaas-plugin
    read: 
      - $SNAP/bin

# The app has no plugs as it is intended to be invoked by the Juju CLI Snap.
apps:
  jaas:
    command: bin/jaas

parts:
  jaas:
    plugin: go
    source: ./
    source-type: git
    stage-packages: [busybox-static]
    prime:
      - bin/jaas
      - bin/busybox
      - bin/static-sh
    override-build: |
      set -e
      CGO_ENABLED=0 go install github.com/canonical/jimm/cmd/jaas
    override-prime: |
      snapcraftctl prime
      ln -sf ./jaas bin/juju-add-service-account
