// GENERATED FILE - DO NOT EDIT
//
// Generated from:
//   Juju Version:   2.9-rc2
//   Module Version: v0.0.0-20201102064548-d344015a21e6

package cloudcred

var attr = map[string]bool{
	"azure\x1einteractive\x1esubscription-id":                   true,
	"azure\x1eservice-principal-secret\x1eapplication-id":       true,
	"azure\x1eservice-principal-secret\x1eapplication-password": false,
	"azure\x1eservice-principal-secret\x1esubscription-id":      true,
	"cloudsigma\x1euserpass\x1epassword":                        false,
	"cloudsigma\x1euserpass\x1eusername":                        true,
	"dummy\x1euserpass\x1epassword":                             false,
	"dummy\x1euserpass\x1eusername":                             true,
	"ec2\x1eaccess-key\x1eaccess-key":                           true,
	"ec2\x1eaccess-key\x1esecret-key":                           false,
	"gce\x1ejsonfile\x1efile":                                   true,
	"gce\x1eoauth2\x1eclient-email":                             true,
	"gce\x1eoauth2\x1eclient-id":                                true,
	"gce\x1eoauth2\x1eprivate-key":                              false,
	"gce\x1eoauth2\x1eproject-id":                               true,
	"kubernetes\x1ecertificate\x1eClientCertificateData":        true,
	"kubernetes\x1ecertificate\x1eToken":                        false,
	"kubernetes\x1ecertificate\x1erbac-id":                      true,
	"kubernetes\x1eoauth2withcert\x1eClientCertificateData":     true,
	"kubernetes\x1eoauth2withcert\x1eClientKeyData":             false,
	"kubernetes\x1eoauth2withcert\x1eToken":                     false,
	"kubernetes\x1euserpass\x1epassword":                        false,
	"kubernetes\x1euserpass\x1eusername":                        true,
	"lxd\x1ecertificate\x1eclient-cert":                         false,
	"lxd\x1ecertificate\x1eclient-key":                          false,
	"lxd\x1ecertificate\x1eserver-cert":                         false,
	"lxd\x1einteractive\x1etrust-password":                      false,
	"maas\x1eoauth1\x1emaas-oauth":                              false,
	"oci\x1ehttpsig\x1efingerprint":                             true,
	"oci\x1ehttpsig\x1ekey":                                     true,
	"oci\x1ehttpsig\x1epass-phrase":                             false,
	"oci\x1ehttpsig\x1eregion":                                  true,
	"oci\x1ehttpsig\x1etenancy":                                 true,
	"oci\x1ehttpsig\x1euser":                                    true,
	"openstack\x1eaccess-key\x1eaccess-key":                     true,
	"openstack\x1eaccess-key\x1esecret-key":                     false,
	"openstack\x1eaccess-key\x1etenant-id":                      true,
	"openstack\x1eaccess-key\x1etenant-name":                    true,
	"openstack\x1eaccess-key\x1eversion":                        true,
	"openstack\x1euserpass\x1edomain-name":                      true,
	"openstack\x1euserpass\x1epassword":                         false,
	"openstack\x1euserpass\x1eproject-domain-name":              true,
	"openstack\x1euserpass\x1etenant-id":                        true,
	"openstack\x1euserpass\x1etenant-name":                      true,
	"openstack\x1euserpass\x1euser-domain-name":                 true,
	"openstack\x1euserpass\x1eusername":                         true,
	"openstack\x1euserpass\x1eversion":                          true,
	"rackspace\x1euserpass\x1epassword":                         false,
	"rackspace\x1euserpass\x1etenant-name":                      true,
	"rackspace\x1euserpass\x1eusername":                         true,
	"vsphere\x1euserpass\x1epassword":                           false,
	"vsphere\x1euserpass\x1euser":                               true,
	"vsphere\x1euserpass\x1evmfolder":                           true,
}
