// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/internal/jimm/offer (interfaces: IdPGroupFetcher)
//
// Generated by this command:
//
//	mockgen -package mocks -typed -destination ./mocks/idpgroupfetcher.go github.com/canonical/jimm/v3/internal/jimm/offer IdPGroupFetcher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIdPGroupFetcher is a mock of IdPGroupFetcher interface.
type MockIdPGroupFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockIdPGroupFetcherMockRecorder
	isgomock struct{}
}

// MockIdPGroupFetcherMockRecorder is the mock recorder for MockIdPGroupFetcher.
type MockIdPGroupFetcherMockRecorder struct {
	mock *MockIdPGroupFetcher
}

// NewMockIdPGroupFetcher creates a new mock instance.
func NewMockIdPGroupFetcher(ctrl *gomock.Controller) *MockIdPGroupFetcher {
	mock := &MockIdPGroupFetcher{ctrl: ctrl}
	mock.recorder = &MockIdPGroupFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdPGroupFetcher) EXPECT() *MockIdPGroupFetcherMockRecorder {
	return m.recorder
}

// FetchGroups mocks base method.
func (m *MockIdPGroupFetcher) FetchGroups(ctx context.Context, username string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchGroups", ctx, username)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchGroups indicates an expected call of FetchGroups.
func (mr *MockIdPGroupFetcherMockRecorder) FetchGroups(ctx, username any) *MockIdPGroupFetcherFetchGroupsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchGroups", reflect.TypeOf((*MockIdPGroupFetcher)(nil).FetchGroups), ctx, username)
	return &MockIdPGroupFetcherFetchGroupsCall{Call: call}
}

// MockIdPGroupFetcherFetchGroupsCall wrap *gomock.Call
type MockIdPGroupFetcherFetchGroupsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIdPGroupFetcherFetchGroupsCall) Return(arg0 []string, arg1 error) *MockIdPGroupFetcherFetchGroupsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIdPGroupFetcherFetchGroupsCall) Do(f func(context.Context, string) ([]string, error)) *MockIdPGroupFetcherFetchGroupsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIdPGroupFetcherFetchGroupsCall) DoAndReturn(f func(context.Context, string) ([]string, error)) *MockIdPGroupFetcherFetchGroupsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
