// Code generated by cmd/facadeversions; DO NOT EDIT.
//
// Source: internal/jujuapi.SupportedFacades()

package jujuapi

// SupportedFacadeVersions is a snapshot of the facade versions registered by this server.
//
// It is generated from runtime registration (see SupportedFacades).
var SupportedFacadeVersions = map[string][]int{
	"ApplicationOffers":   []int{4},
	"Cloud":               []int{7},
	"Controller":          []int{11},
	"JIMM":                []int{4},
	"MigrationTarget":     []int{4},
	"ModelConfig":         []int{3},
	"ModelManager":        []int{9},
	"ModelSummaryWatcher": []int{1},
	"Pinger":              []int{1},
	"UserManager":         []int{3},
}
