// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/internal/jujuapi (interfaces: streamLoginManager)
//
// Generated by this command:
//
//	mockgen -package jujuapi -typed -mock_names streamLoginManager=MockStreamLoginManager -destination ./streamauthentication_mock_test.go . streamLoginManager
//

// Package jujuapi is a generated GoMock package.
package jujuapi

import (
	context "context"
	reflect "reflect"

	openfga "github.com/canonical/jimm/v3/internal/openfga"
	gomock "go.uber.org/mock/gomock"
)

// MockStreamLoginManager is a mock of streamLoginManager interface.
type MockStreamLoginManager struct {
	ctrl     *gomock.Controller
	recorder *MockStreamLoginManagerMockRecorder
	isgomock struct{}
}

// MockStreamLoginManagerMockRecorder is the mock recorder for MockStreamLoginManager.
type MockStreamLoginManagerMockRecorder struct {
	mock *MockStreamLoginManager
}

// NewMockStreamLoginManager creates a new mock instance.
func NewMockStreamLoginManager(ctrl *gomock.Controller) *MockStreamLoginManager {
	mock := &MockStreamLoginManager{ctrl: ctrl}
	mock.recorder = &MockStreamLoginManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamLoginManager) EXPECT() *MockStreamLoginManagerMockRecorder {
	return m.recorder
}

// LoginClientCredentials mocks base method.
func (m *MockStreamLoginManager) LoginClientCredentials(ctx context.Context, clientID, clientSecret string) (*openfga.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginClientCredentials", ctx, clientID, clientSecret)
	ret0, _ := ret[0].(*openfga.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginClientCredentials indicates an expected call of LoginClientCredentials.
func (mr *MockStreamLoginManagerMockRecorder) LoginClientCredentials(ctx, clientID, clientSecret any) *MockStreamLoginManagerLoginClientCredentialsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginClientCredentials", reflect.TypeOf((*MockStreamLoginManager)(nil).LoginClientCredentials), ctx, clientID, clientSecret)
	return &MockStreamLoginManagerLoginClientCredentialsCall{Call: call}
}

// MockStreamLoginManagerLoginClientCredentialsCall wrap *gomock.Call
type MockStreamLoginManagerLoginClientCredentialsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStreamLoginManagerLoginClientCredentialsCall) Return(arg0 *openfga.User, arg1 error) *MockStreamLoginManagerLoginClientCredentialsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStreamLoginManagerLoginClientCredentialsCall) Do(f func(context.Context, string, string) (*openfga.User, error)) *MockStreamLoginManagerLoginClientCredentialsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStreamLoginManagerLoginClientCredentialsCall) DoAndReturn(f func(context.Context, string, string) (*openfga.User, error)) *MockStreamLoginManagerLoginClientCredentialsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LoginWithSessionToken mocks base method.
func (m *MockStreamLoginManager) LoginWithSessionToken(ctx context.Context, sessionToken string) (*openfga.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginWithSessionToken", ctx, sessionToken)
	ret0, _ := ret[0].(*openfga.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginWithSessionToken indicates an expected call of LoginWithSessionToken.
func (mr *MockStreamLoginManagerMockRecorder) LoginWithSessionToken(ctx, sessionToken any) *MockStreamLoginManagerLoginWithSessionTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginWithSessionToken", reflect.TypeOf((*MockStreamLoginManager)(nil).LoginWithSessionToken), ctx, sessionToken)
	return &MockStreamLoginManagerLoginWithSessionTokenCall{Call: call}
}

// MockStreamLoginManagerLoginWithSessionTokenCall wrap *gomock.Call
type MockStreamLoginManagerLoginWithSessionTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStreamLoginManagerLoginWithSessionTokenCall) Return(arg0 *openfga.User, arg1 error) *MockStreamLoginManagerLoginWithSessionTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStreamLoginManagerLoginWithSessionTokenCall) Do(f func(context.Context, string) (*openfga.User, error)) *MockStreamLoginManagerLoginWithSessionTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStreamLoginManagerLoginWithSessionTokenCall) DoAndReturn(f func(context.Context, string) (*openfga.User, error)) *MockStreamLoginManagerLoginWithSessionTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
