// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/internal/jujuclient (interfaces: SummaryWatcher)
//
// Generated by this command:
//
//	mockgen -package mocks -typed -destination ./mocks/watcher_mock.go github.com/canonical/jimm/v3/internal/jujuclient SummaryWatcher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	params "github.com/juju/juju/rpc/params"
	gomock "go.uber.org/mock/gomock"
)

// MockSummaryWatcher is a mock of SummaryWatcher interface.
type MockSummaryWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockSummaryWatcherMockRecorder
	isgomock struct{}
}

// MockSummaryWatcherMockRecorder is the mock recorder for MockSummaryWatcher.
type MockSummaryWatcherMockRecorder struct {
	mock *MockSummaryWatcher
}

// NewMockSummaryWatcher creates a new mock instance.
func NewMockSummaryWatcher(ctrl *gomock.Controller) *MockSummaryWatcher {
	mock := &MockSummaryWatcher{ctrl: ctrl}
	mock.recorder = &MockSummaryWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSummaryWatcher) EXPECT() *MockSummaryWatcherMockRecorder {
	return m.recorder
}

// Next mocks base method.
func (m *MockSummaryWatcher) Next() ([]params.ModelAbstract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].([]params.ModelAbstract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Next indicates an expected call of Next.
func (mr *MockSummaryWatcherMockRecorder) Next() *MockSummaryWatcherNextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockSummaryWatcher)(nil).Next))
	return &MockSummaryWatcherNextCall{Call: call}
}

// MockSummaryWatcherNextCall wrap *gomock.Call
type MockSummaryWatcherNextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSummaryWatcherNextCall) Return(arg0 []params.ModelAbstract, arg1 error) *MockSummaryWatcherNextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSummaryWatcherNextCall) Do(f func() ([]params.ModelAbstract, error)) *MockSummaryWatcherNextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSummaryWatcherNextCall) DoAndReturn(f func() ([]params.ModelAbstract, error)) *MockSummaryWatcherNextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Stop mocks base method.
func (m *MockSummaryWatcher) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockSummaryWatcherMockRecorder) Stop() *MockSummaryWatcherStopCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSummaryWatcher)(nil).Stop))
	return &MockSummaryWatcherStopCall{Call: call}
}

// MockSummaryWatcherStopCall wrap *gomock.Call
type MockSummaryWatcherStopCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSummaryWatcherStopCall) Return(arg0 error) *MockSummaryWatcherStopCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSummaryWatcherStopCall) Do(f func() error) *MockSummaryWatcherStopCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSummaryWatcherStopCall) DoAndReturn(f func() error) *MockSummaryWatcherStopCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
