// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/internal/river (interfaces: UpgradeToManager)
//
// Generated by this command:
//
//	mockgen -package river_test -typed -destination ./river_mock_test.go github.com/canonical/jimm/v3/internal/river UpgradeToManager
//

// Package river_test is a generated GoMock package.
package river_test

import (
	context "context"
	reflect "reflect"

	openfga "github.com/canonical/jimm/v3/internal/openfga"
	version "github.com/juju/version/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockUpgradeToManager is a mock of UpgradeToManager interface.
type MockUpgradeToManager struct {
	ctrl     *gomock.Controller
	recorder *MockUpgradeToManagerMockRecorder
	isgomock struct{}
}

// MockUpgradeToManagerMockRecorder is the mock recorder for MockUpgradeToManager.
type MockUpgradeToManagerMockRecorder struct {
	mock *MockUpgradeToManager
}

// NewMockUpgradeToManager creates a new mock instance.
func NewMockUpgradeToManager(ctrl *gomock.Controller) *MockUpgradeToManager {
	mock := &MockUpgradeToManager{ctrl: ctrl}
	mock.recorder = &MockUpgradeToManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpgradeToManager) EXPECT() *MockUpgradeToManagerMockRecorder {
	return m.recorder
}

// UpgradeTo mocks base method.
func (m *MockUpgradeToManager) UpgradeTo(ctx context.Context, user *openfga.User, modelUUID string, targetVersion version.Number) (version.Number, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpgradeTo", ctx, user, modelUUID, targetVersion)
	ret0, _ := ret[0].(version.Number)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpgradeTo indicates an expected call of UpgradeTo.
func (mr *MockUpgradeToManagerMockRecorder) UpgradeTo(ctx, user, modelUUID, targetVersion any) *MockUpgradeToManagerUpgradeToCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpgradeTo", reflect.TypeOf((*MockUpgradeToManager)(nil).UpgradeTo), ctx, user, modelUUID, targetVersion)
	return &MockUpgradeToManagerUpgradeToCall{Call: call}
}

// MockUpgradeToManagerUpgradeToCall wrap *gomock.Call
type MockUpgradeToManagerUpgradeToCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpgradeToManagerUpgradeToCall) Return(arg0 version.Number, arg1 error) *MockUpgradeToManagerUpgradeToCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpgradeToManagerUpgradeToCall) Do(f func(context.Context, *openfga.User, string, version.Number) (version.Number, error)) *MockUpgradeToManagerUpgradeToCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpgradeToManagerUpgradeToCall) DoAndReturn(f func(context.Context, *openfga.User, string, version.Number) (version.Number, error)) *MockUpgradeToManagerUpgradeToCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
