// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/internal/river (interfaces: UpgradeManager)
//
// Generated by this command:
//
//	mockgen -package river -typed -destination ./river_mock_test.go github.com/canonical/jimm/v3/internal/river UpgradeManager
//

// Package river is a generated GoMock package.
package river

import (
	context "context"
	reflect "reflect"

	openfga "github.com/canonical/jimm/v3/internal/openfga"
	gomock "go.uber.org/mock/gomock"
)

// MockUpgradeManager is a mock of UpgradeManager interface.
type MockUpgradeManager struct {
	ctrl     *gomock.Controller
	recorder *MockUpgradeManagerMockRecorder
	isgomock struct{}
}

// MockUpgradeManagerMockRecorder is the mock recorder for MockUpgradeManager.
type MockUpgradeManagerMockRecorder struct {
	mock *MockUpgradeManager
}

// NewMockUpgradeManager creates a new mock instance.
func NewMockUpgradeManager(ctrl *gomock.Controller) *MockUpgradeManager {
	mock := &MockUpgradeManager{ctrl: ctrl}
	mock.recorder = &MockUpgradeManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpgradeManager) EXPECT() *MockUpgradeManagerMockRecorder {
	return m.recorder
}

// MigrateModel mocks base method.
func (m *MockUpgradeManager) MigrateModel(ctx context.Context, user *openfga.User, modelUUID, targetControllerName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrateModel", ctx, user, modelUUID, targetControllerName)
	ret0, _ := ret[0].(error)
	return ret0
}

// MigrateModel indicates an expected call of MigrateModel.
func (mr *MockUpgradeManagerMockRecorder) MigrateModel(ctx, user, modelUUID, targetControllerName any) *MockUpgradeManagerMigrateModelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrateModel", reflect.TypeOf((*MockUpgradeManager)(nil).MigrateModel), ctx, user, modelUUID, targetControllerName)
	return &MockUpgradeManagerMigrateModelCall{Call: call}
}

// MockUpgradeManagerMigrateModelCall wrap *gomock.Call
type MockUpgradeManagerMigrateModelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpgradeManagerMigrateModelCall) Return(arg0 error) *MockUpgradeManagerMigrateModelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpgradeManagerMigrateModelCall) Do(f func(context.Context, *openfga.User, string, string) error) *MockUpgradeManagerMigrateModelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpgradeManagerMigrateModelCall) DoAndReturn(f func(context.Context, *openfga.User, string, string) error) *MockUpgradeManagerMigrateModelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
