name: jimm
summary: Juju Intelligent Model Manager
description: Multi-cloud controller for managing JAAS models.
grade: stable
base: core20
confinement: strict
adopt-info: jimmsrv # Version our app via set-version within an override

apps:
  jimm:
    command: bin/jimmsrv
    plugs:
      - network
      - network-bind

parts:
  jimmsrv:
    plugin: go
    source: ./
    build-packages:
      - git
      - gcc
    override-pull: |-
      set -e
      snapcraftctl pull
      mkdir -p $SNAPCRAFT_PART_SRC/version
      git -C $SNAPCRAFT_PART_SRC rev-parse --verify HEAD | tee $SNAPCRAFT_PART_SRC/version/commit.txt
      git -C $SNAPCRAFT_PART_SRC describe --dirty --abbrev=0 | tee $SNAPCRAFT_PART_SRC/version/version.txt
      snapcraftctl set-version `cat $SNAPCRAFT_PART_SRC/version/version.txt`
    override-build: |-
      set -e
      go install -mod readonly -ldflags '-linkmode=external' -tags version github.com/CanonicalLtd/jimm/cmd/jimmsrv
