name: jimm
version: '0.26.0'
summary: Juju Intelligent Model Manager
description: Multi-cloud controller for managing JAAS models.
grade: stable
base: core18
confinement: strict

apps:
  jimm:
    command: bin/wrappers/jimm
    daemon: simple
    plugs:
     - network
     - network-bind

parts:
  jimm:
    plugin: go
    source: .
    go-packages:
    - github.com/CanonicalLtd/jimm
    go-importpath: github.com/CanonicalLtd/jimm
    build-packages:
    - git
    - gcc
    override-build: |-
      set -ex
      ls -lah ~/src
      ls -lah ~/src/version
      GIT_COMMIT=`git -C $SNAPCRAFT_PART_SRC rev-parse --verify HEAD`
      GIT_VERSION=`git -C $SNAPCRAFT_PART_SRC describe --dirty --abbrev=0`
      cp ~/src/version/init.go.tmpl ~/src/version/init.go
      gofmt -w -r "unknownVersion -> Version{GitCommit: \"${GIT_COMMIT}\", Version: \"${GIT_VERSION}\",}" ~/src/version/init.go
      go build -a github.com/CanonicalLtd/jimm/cmd/jemd

  files:
    plugin: dump
    source: files
    organize:
      config.yaml: etc/jimm/config.yaml
      jimm.wrapper: bin/wrappers/jimm
    prime:
    - etc/jimm/config.yaml
    - bin/wrappers/jimm
