// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/internal/jimm/upgrade (interfaces: UpgradeManagerAPI)
//
// Generated by this command:
//
//	mockgen -typed -destination=./mocks/api.go -package=mocks . UpgradeManagerAPI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	url "net/url"
	reflect "reflect"

	base "github.com/juju/juju/api/base"
	cloud "github.com/juju/juju/cloud"
	params "github.com/juju/juju/rpc/params"
	names "github.com/juju/names/v5"
	gomock "go.uber.org/mock/gomock"
	httprequest "gopkg.in/httprequest.v1"
)

// MockUpgradeManagerAPI is a mock of UpgradeManagerAPI interface.
type MockUpgradeManagerAPI struct {
	ctrl     *gomock.Controller
	recorder *MockUpgradeManagerAPIMockRecorder
	isgomock struct{}
}

// MockUpgradeManagerAPIMockRecorder is the mock recorder for MockUpgradeManagerAPI.
type MockUpgradeManagerAPIMockRecorder struct {
	mock *MockUpgradeManagerAPI
}

// NewMockUpgradeManagerAPI creates a new mock instance.
func NewMockUpgradeManagerAPI(ctrl *gomock.Controller) *MockUpgradeManagerAPI {
	mock := &MockUpgradeManagerAPI{ctrl: ctrl}
	mock.recorder = &MockUpgradeManagerAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpgradeManagerAPI) EXPECT() *MockUpgradeManagerAPIMockRecorder {
	return m.recorder
}

// APICall mocks base method.
func (m *MockUpgradeManagerAPI) APICall(objType string, version int, id, request string, arg4, response any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APICall", objType, version, id, request, arg4, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// APICall indicates an expected call of APICall.
func (mr *MockUpgradeManagerAPIMockRecorder) APICall(objType, version, id, request, arg4, response any) *MockUpgradeManagerAPIAPICallCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APICall", reflect.TypeOf((*MockUpgradeManagerAPI)(nil).APICall), objType, version, id, request, arg4, response)
	return &MockUpgradeManagerAPIAPICallCall{Call: call}
}

// MockUpgradeManagerAPIAPICallCall wrap *gomock.Call
type MockUpgradeManagerAPIAPICallCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpgradeManagerAPIAPICallCall) Return(arg0 error) *MockUpgradeManagerAPIAPICallCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpgradeManagerAPIAPICallCall) Do(f func(string, int, string, string, any, any) error) *MockUpgradeManagerAPIAPICallCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpgradeManagerAPIAPICallCall) DoAndReturn(f func(string, int, string, string, any, any) error) *MockUpgradeManagerAPIAPICallCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BakeryClient mocks base method.
func (m *MockUpgradeManagerAPI) BakeryClient() base.MacaroonDischarger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BakeryClient")
	ret0, _ := ret[0].(base.MacaroonDischarger)
	return ret0
}

// BakeryClient indicates an expected call of BakeryClient.
func (mr *MockUpgradeManagerAPIMockRecorder) BakeryClient() *MockUpgradeManagerAPIBakeryClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BakeryClient", reflect.TypeOf((*MockUpgradeManagerAPI)(nil).BakeryClient))
	return &MockUpgradeManagerAPIBakeryClientCall{Call: call}
}

// MockUpgradeManagerAPIBakeryClientCall wrap *gomock.Call
type MockUpgradeManagerAPIBakeryClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpgradeManagerAPIBakeryClientCall) Return(arg0 base.MacaroonDischarger) *MockUpgradeManagerAPIBakeryClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpgradeManagerAPIBakeryClientCall) Do(f func() base.MacaroonDischarger) *MockUpgradeManagerAPIBakeryClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpgradeManagerAPIBakeryClientCall) DoAndReturn(f func() base.MacaroonDischarger) *MockUpgradeManagerAPIBakeryClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BestFacadeVersion mocks base method.
func (m *MockUpgradeManagerAPI) BestFacadeVersion(facade string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BestFacadeVersion", facade)
	ret0, _ := ret[0].(int)
	return ret0
}

// BestFacadeVersion indicates an expected call of BestFacadeVersion.
func (mr *MockUpgradeManagerAPIMockRecorder) BestFacadeVersion(facade any) *MockUpgradeManagerAPIBestFacadeVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BestFacadeVersion", reflect.TypeOf((*MockUpgradeManagerAPI)(nil).BestFacadeVersion), facade)
	return &MockUpgradeManagerAPIBestFacadeVersionCall{Call: call}
}

// MockUpgradeManagerAPIBestFacadeVersionCall wrap *gomock.Call
type MockUpgradeManagerAPIBestFacadeVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpgradeManagerAPIBestFacadeVersionCall) Return(arg0 int) *MockUpgradeManagerAPIBestFacadeVersionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpgradeManagerAPIBestFacadeVersionCall) Do(f func(string) int) *MockUpgradeManagerAPIBestFacadeVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpgradeManagerAPIBestFacadeVersionCall) DoAndReturn(f func(string) int) *MockUpgradeManagerAPIBestFacadeVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Close mocks base method.
func (m *MockUpgradeManagerAPI) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockUpgradeManagerAPIMockRecorder) Close() *MockUpgradeManagerAPICloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockUpgradeManagerAPI)(nil).Close))
	return &MockUpgradeManagerAPICloseCall{Call: call}
}

// MockUpgradeManagerAPICloseCall wrap *gomock.Call
type MockUpgradeManagerAPICloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpgradeManagerAPICloseCall) Return(arg0 error) *MockUpgradeManagerAPICloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpgradeManagerAPICloseCall) Do(f func() error) *MockUpgradeManagerAPICloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpgradeManagerAPICloseCall) DoAndReturn(f func() error) *MockUpgradeManagerAPICloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Cloud mocks base method.
func (m *MockUpgradeManagerAPI) Cloud(tag names.CloudTag, arg1 *cloud.Cloud) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cloud", tag, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cloud indicates an expected call of Cloud.
func (mr *MockUpgradeManagerAPIMockRecorder) Cloud(tag, arg1 any) *MockUpgradeManagerAPICloudCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cloud", reflect.TypeOf((*MockUpgradeManagerAPI)(nil).Cloud), tag, arg1)
	return &MockUpgradeManagerAPICloudCall{Call: call}
}

// MockUpgradeManagerAPICloudCall wrap *gomock.Call
type MockUpgradeManagerAPICloudCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpgradeManagerAPICloudCall) Return(arg0 error) *MockUpgradeManagerAPICloudCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpgradeManagerAPICloudCall) Do(f func(names.CloudTag, *cloud.Cloud) error) *MockUpgradeManagerAPICloudCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpgradeManagerAPICloudCall) DoAndReturn(f func(names.CloudTag, *cloud.Cloud) error) *MockUpgradeManagerAPICloudCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ConnectControllerStream mocks base method.
func (m *MockUpgradeManagerAPI) ConnectControllerStream(path string, attrs url.Values, headers http.Header) (base.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectControllerStream", path, attrs, headers)
	ret0, _ := ret[0].(base.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConnectControllerStream indicates an expected call of ConnectControllerStream.
func (mr *MockUpgradeManagerAPIMockRecorder) ConnectControllerStream(path, attrs, headers any) *MockUpgradeManagerAPIConnectControllerStreamCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectControllerStream", reflect.TypeOf((*MockUpgradeManagerAPI)(nil).ConnectControllerStream), path, attrs, headers)
	return &MockUpgradeManagerAPIConnectControllerStreamCall{Call: call}
}

// MockUpgradeManagerAPIConnectControllerStreamCall wrap *gomock.Call
type MockUpgradeManagerAPIConnectControllerStreamCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpgradeManagerAPIConnectControllerStreamCall) Return(arg0 base.Stream, arg1 error) *MockUpgradeManagerAPIConnectControllerStreamCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpgradeManagerAPIConnectControllerStreamCall) Do(f func(string, url.Values, http.Header) (base.Stream, error)) *MockUpgradeManagerAPIConnectControllerStreamCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpgradeManagerAPIConnectControllerStreamCall) DoAndReturn(f func(string, url.Values, http.Header) (base.Stream, error)) *MockUpgradeManagerAPIConnectControllerStreamCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ConnectStream mocks base method.
func (m *MockUpgradeManagerAPI) ConnectStream(path string, attrs url.Values) (base.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectStream", path, attrs)
	ret0, _ := ret[0].(base.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConnectStream indicates an expected call of ConnectStream.
func (mr *MockUpgradeManagerAPIMockRecorder) ConnectStream(path, attrs any) *MockUpgradeManagerAPIConnectStreamCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectStream", reflect.TypeOf((*MockUpgradeManagerAPI)(nil).ConnectStream), path, attrs)
	return &MockUpgradeManagerAPIConnectStreamCall{Call: call}
}

// MockUpgradeManagerAPIConnectStreamCall wrap *gomock.Call
type MockUpgradeManagerAPIConnectStreamCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpgradeManagerAPIConnectStreamCall) Return(arg0 base.Stream, arg1 error) *MockUpgradeManagerAPIConnectStreamCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpgradeManagerAPIConnectStreamCall) Do(f func(string, url.Values) (base.Stream, error)) *MockUpgradeManagerAPIConnectStreamCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpgradeManagerAPIConnectStreamCall) DoAndReturn(f func(string, url.Values) (base.Stream, error)) *MockUpgradeManagerAPIConnectStreamCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Context mocks base method.
func (m *MockUpgradeManagerAPI) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockUpgradeManagerAPIMockRecorder) Context() *MockUpgradeManagerAPIContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockUpgradeManagerAPI)(nil).Context))
	return &MockUpgradeManagerAPIContextCall{Call: call}
}

// MockUpgradeManagerAPIContextCall wrap *gomock.Call
type MockUpgradeManagerAPIContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpgradeManagerAPIContextCall) Return(arg0 context.Context) *MockUpgradeManagerAPIContextCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpgradeManagerAPIContextCall) Do(f func() context.Context) *MockUpgradeManagerAPIContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpgradeManagerAPIContextCall) DoAndReturn(f func() context.Context) *MockUpgradeManagerAPIContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ControllerModelSummary mocks base method.
func (m *MockUpgradeManagerAPI) ControllerModelSummary(arg0 context.Context, arg1 *params.ModelSummary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ControllerModelSummary", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ControllerModelSummary indicates an expected call of ControllerModelSummary.
func (mr *MockUpgradeManagerAPIMockRecorder) ControllerModelSummary(arg0, arg1 any) *MockUpgradeManagerAPIControllerModelSummaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ControllerModelSummary", reflect.TypeOf((*MockUpgradeManagerAPI)(nil).ControllerModelSummary), arg0, arg1)
	return &MockUpgradeManagerAPIControllerModelSummaryCall{Call: call}
}

// MockUpgradeManagerAPIControllerModelSummaryCall wrap *gomock.Call
type MockUpgradeManagerAPIControllerModelSummaryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpgradeManagerAPIControllerModelSummaryCall) Return(arg0 error) *MockUpgradeManagerAPIControllerModelSummaryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpgradeManagerAPIControllerModelSummaryCall) Do(f func(context.Context, *params.ModelSummary) error) *MockUpgradeManagerAPIControllerModelSummaryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpgradeManagerAPIControllerModelSummaryCall) DoAndReturn(f func(context.Context, *params.ModelSummary) error) *MockUpgradeManagerAPIControllerModelSummaryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CredentialContents mocks base method.
func (m *MockUpgradeManagerAPI) CredentialContents(arg0, credential string, withSecrets bool) ([]params.CredentialContentResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CredentialContents", arg0, credential, withSecrets)
	ret0, _ := ret[0].([]params.CredentialContentResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CredentialContents indicates an expected call of CredentialContents.
func (mr *MockUpgradeManagerAPIMockRecorder) CredentialContents(arg0, credential, withSecrets any) *MockUpgradeManagerAPICredentialContentsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CredentialContents", reflect.TypeOf((*MockUpgradeManagerAPI)(nil).CredentialContents), arg0, credential, withSecrets)
	return &MockUpgradeManagerAPICredentialContentsCall{Call: call}
}

// MockUpgradeManagerAPICredentialContentsCall wrap *gomock.Call
type MockUpgradeManagerAPICredentialContentsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpgradeManagerAPICredentialContentsCall) Return(arg0 []params.CredentialContentResult, arg1 error) *MockUpgradeManagerAPICredentialContentsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpgradeManagerAPICredentialContentsCall) Do(f func(string, string, bool) ([]params.CredentialContentResult, error)) *MockUpgradeManagerAPICredentialContentsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpgradeManagerAPICredentialContentsCall) DoAndReturn(f func(string, string, bool) ([]params.CredentialContentResult, error)) *MockUpgradeManagerAPICredentialContentsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HTTPClient mocks base method.
func (m *MockUpgradeManagerAPI) HTTPClient() (*httprequest.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTTPClient")
	ret0, _ := ret[0].(*httprequest.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HTTPClient indicates an expected call of HTTPClient.
func (mr *MockUpgradeManagerAPIMockRecorder) HTTPClient() *MockUpgradeManagerAPIHTTPClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTTPClient", reflect.TypeOf((*MockUpgradeManagerAPI)(nil).HTTPClient))
	return &MockUpgradeManagerAPIHTTPClientCall{Call: call}
}

// MockUpgradeManagerAPIHTTPClientCall wrap *gomock.Call
type MockUpgradeManagerAPIHTTPClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpgradeManagerAPIHTTPClientCall) Return(arg0 *httprequest.Client, arg1 error) *MockUpgradeManagerAPIHTTPClientCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpgradeManagerAPIHTTPClientCall) Do(f func() (*httprequest.Client, error)) *MockUpgradeManagerAPIHTTPClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpgradeManagerAPIHTTPClientCall) DoAndReturn(f func() (*httprequest.Client, error)) *MockUpgradeManagerAPIHTTPClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ModelTag mocks base method.
func (m *MockUpgradeManagerAPI) ModelTag() (names.ModelTag, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelTag")
	ret0, _ := ret[0].(names.ModelTag)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ModelTag indicates an expected call of ModelTag.
func (mr *MockUpgradeManagerAPIMockRecorder) ModelTag() *MockUpgradeManagerAPIModelTagCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelTag", reflect.TypeOf((*MockUpgradeManagerAPI)(nil).ModelTag))
	return &MockUpgradeManagerAPIModelTagCall{Call: call}
}

// MockUpgradeManagerAPIModelTagCall wrap *gomock.Call
type MockUpgradeManagerAPIModelTagCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpgradeManagerAPIModelTagCall) Return(arg0 names.ModelTag, arg1 bool) *MockUpgradeManagerAPIModelTagCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpgradeManagerAPIModelTagCall) Do(f func() (names.ModelTag, bool)) *MockUpgradeManagerAPIModelTagCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpgradeManagerAPIModelTagCall) DoAndReturn(f func() (names.ModelTag, bool)) *MockUpgradeManagerAPIModelTagCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RootHTTPClient mocks base method.
func (m *MockUpgradeManagerAPI) RootHTTPClient() (*httprequest.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RootHTTPClient")
	ret0, _ := ret[0].(*httprequest.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RootHTTPClient indicates an expected call of RootHTTPClient.
func (mr *MockUpgradeManagerAPIMockRecorder) RootHTTPClient() *MockUpgradeManagerAPIRootHTTPClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RootHTTPClient", reflect.TypeOf((*MockUpgradeManagerAPI)(nil).RootHTTPClient))
	return &MockUpgradeManagerAPIRootHTTPClientCall{Call: call}
}

// MockUpgradeManagerAPIRootHTTPClientCall wrap *gomock.Call
type MockUpgradeManagerAPIRootHTTPClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpgradeManagerAPIRootHTTPClientCall) Return(arg0 *httprequest.Client, arg1 error) *MockUpgradeManagerAPIRootHTTPClientCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpgradeManagerAPIRootHTTPClientCall) Do(f func() (*httprequest.Client, error)) *MockUpgradeManagerAPIRootHTTPClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpgradeManagerAPIRootHTTPClientCall) DoAndReturn(f func() (*httprequest.Client, error)) *MockUpgradeManagerAPIRootHTTPClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
