// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/internal/jimm/juju (interfaces: API)
//
// Generated by this command:
//
//	mockgen -typed -destination=./mocks/api.go -package=mocks github.com/canonical/jimm/v3/internal/jimm/juju API
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	url "net/url"
	reflect "reflect"
	time "time"

	bakery "github.com/go-macaroon-bakery/macaroon-bakery/v3/bakery"
	base "github.com/juju/juju/api/base"
	cloud "github.com/juju/juju/cloud"
	crossmodel "github.com/juju/juju/core/crossmodel"
	migration "github.com/juju/juju/core/migration"
	params "github.com/juju/juju/rpc/params"
	names "github.com/juju/names/v5"
	version "github.com/juju/version/v2"
	gomock "go.uber.org/mock/gomock"
	httprequest "gopkg.in/httprequest.v1"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
	isgomock struct{}
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// APICall mocks base method.
func (m *MockAPI) APICall(objType string, arg1 int, id, request string, arg4, response any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APICall", objType, arg1, id, request, arg4, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// APICall indicates an expected call of APICall.
func (mr *MockAPIMockRecorder) APICall(objType, arg1, id, request, arg4, response any) *MockAPIAPICallCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APICall", reflect.TypeOf((*MockAPI)(nil).APICall), objType, arg1, id, request, arg4, response)
	return &MockAPIAPICallCall{Call: call}
}

// MockAPIAPICallCall wrap *gomock.Call
type MockAPIAPICallCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIAPICallCall) Return(arg0 error) *MockAPIAPICallCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIAPICallCall) Do(f func(string, int, string, string, any, any) error) *MockAPIAPICallCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIAPICallCall) DoAndReturn(f func(string, int, string, string, any, any) error) *MockAPIAPICallCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Abort mocks base method.
func (m *MockAPI) Abort(modelUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Abort", modelUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Abort indicates an expected call of Abort.
func (mr *MockAPIMockRecorder) Abort(modelUUID any) *MockAPIAbortCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Abort", reflect.TypeOf((*MockAPI)(nil).Abort), modelUUID)
	return &MockAPIAbortCall{Call: call}
}

// MockAPIAbortCall wrap *gomock.Call
type MockAPIAbortCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIAbortCall) Return(arg0 error) *MockAPIAbortCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIAbortCall) Do(f func(string) error) *MockAPIAbortCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIAbortCall) DoAndReturn(f func(string) error) *MockAPIAbortCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Activate mocks base method.
func (m *MockAPI) Activate(modelUUID string, sourceInfo migration.SourceControllerInfo, relatedModels []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activate", modelUUID, sourceInfo, relatedModels)
	ret0, _ := ret[0].(error)
	return ret0
}

// Activate indicates an expected call of Activate.
func (mr *MockAPIMockRecorder) Activate(modelUUID, sourceInfo, relatedModels any) *MockAPIActivateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockAPI)(nil).Activate), modelUUID, sourceInfo, relatedModels)
	return &MockAPIActivateCall{Call: call}
}

// MockAPIActivateCall wrap *gomock.Call
type MockAPIActivateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIActivateCall) Return(arg0 error) *MockAPIActivateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIActivateCall) Do(f func(string, migration.SourceControllerInfo, []string) error) *MockAPIActivateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIActivateCall) DoAndReturn(f func(string, migration.SourceControllerInfo, []string) error) *MockAPIActivateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddCloud mocks base method.
func (m *MockAPI) AddCloud(arg0 names.CloudTag, arg1 cloud.Cloud, arg2 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCloud", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCloud indicates an expected call of AddCloud.
func (mr *MockAPIMockRecorder) AddCloud(arg0, arg1, arg2 any) *MockAPIAddCloudCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCloud", reflect.TypeOf((*MockAPI)(nil).AddCloud), arg0, arg1, arg2)
	return &MockAPIAddCloudCall{Call: call}
}

// MockAPIAddCloudCall wrap *gomock.Call
type MockAPIAddCloudCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIAddCloudCall) Return(arg0 error) *MockAPIAddCloudCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIAddCloudCall) Do(f func(names.CloudTag, cloud.Cloud, bool) error) *MockAPIAddCloudCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIAddCloudCall) DoAndReturn(f func(names.CloudTag, cloud.Cloud, bool) error) *MockAPIAddCloudCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AdoptResources mocks base method.
func (m *MockAPI) AdoptResources(modelUUID string, controllerVersion version.Number) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdoptResources", modelUUID, controllerVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdoptResources indicates an expected call of AdoptResources.
func (mr *MockAPIMockRecorder) AdoptResources(modelUUID, controllerVersion any) *MockAPIAdoptResourcesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdoptResources", reflect.TypeOf((*MockAPI)(nil).AdoptResources), modelUUID, controllerVersion)
	return &MockAPIAdoptResourcesCall{Call: call}
}

// MockAPIAdoptResourcesCall wrap *gomock.Call
type MockAPIAdoptResourcesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIAdoptResourcesCall) Return(arg0 error) *MockAPIAdoptResourcesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIAdoptResourcesCall) Do(f func(string, version.Number) error) *MockAPIAdoptResourcesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIAdoptResourcesCall) DoAndReturn(f func(string, version.Number) error) *MockAPIAdoptResourcesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BakeryClient mocks base method.
func (m *MockAPI) BakeryClient() base.MacaroonDischarger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BakeryClient")
	ret0, _ := ret[0].(base.MacaroonDischarger)
	return ret0
}

// BakeryClient indicates an expected call of BakeryClient.
func (mr *MockAPIMockRecorder) BakeryClient() *MockAPIBakeryClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BakeryClient", reflect.TypeOf((*MockAPI)(nil).BakeryClient))
	return &MockAPIBakeryClientCall{Call: call}
}

// MockAPIBakeryClientCall wrap *gomock.Call
type MockAPIBakeryClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIBakeryClientCall) Return(arg0 base.MacaroonDischarger) *MockAPIBakeryClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIBakeryClientCall) Do(f func() base.MacaroonDischarger) *MockAPIBakeryClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIBakeryClientCall) DoAndReturn(f func() base.MacaroonDischarger) *MockAPIBakeryClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BestFacadeVersion mocks base method.
func (m *MockAPI) BestFacadeVersion(facade string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BestFacadeVersion", facade)
	ret0, _ := ret[0].(int)
	return ret0
}

// BestFacadeVersion indicates an expected call of BestFacadeVersion.
func (mr *MockAPIMockRecorder) BestFacadeVersion(facade any) *MockAPIBestFacadeVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BestFacadeVersion", reflect.TypeOf((*MockAPI)(nil).BestFacadeVersion), facade)
	return &MockAPIBestFacadeVersionCall{Call: call}
}

// MockAPIBestFacadeVersionCall wrap *gomock.Call
type MockAPIBestFacadeVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIBestFacadeVersionCall) Return(arg0 int) *MockAPIBestFacadeVersionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIBestFacadeVersionCall) Do(f func(string) int) *MockAPIBestFacadeVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIBestFacadeVersionCall) DoAndReturn(f func(string) int) *MockAPIBestFacadeVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ChangeModelCredential mocks base method.
func (m *MockAPI) ChangeModelCredential(arg0 context.Context, arg1 names.ModelTag, arg2 names.CloudCredentialTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeModelCredential", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeModelCredential indicates an expected call of ChangeModelCredential.
func (mr *MockAPIMockRecorder) ChangeModelCredential(arg0, arg1, arg2 any) *MockAPIChangeModelCredentialCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeModelCredential", reflect.TypeOf((*MockAPI)(nil).ChangeModelCredential), arg0, arg1, arg2)
	return &MockAPIChangeModelCredentialCall{Call: call}
}

// MockAPIChangeModelCredentialCall wrap *gomock.Call
type MockAPIChangeModelCredentialCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIChangeModelCredentialCall) Return(arg0 error) *MockAPIChangeModelCredentialCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIChangeModelCredentialCall) Do(f func(context.Context, names.ModelTag, names.CloudCredentialTag) error) *MockAPIChangeModelCredentialCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIChangeModelCredentialCall) DoAndReturn(f func(context.Context, names.ModelTag, names.CloudCredentialTag) error) *MockAPIChangeModelCredentialCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CheckCredentialModels mocks base method.
func (m *MockAPI) CheckCredentialModels(arg0 context.Context, arg1 params.TaggedCredential) ([]params.UpdateCredentialModelResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCredentialModels", arg0, arg1)
	ret0, _ := ret[0].([]params.UpdateCredentialModelResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCredentialModels indicates an expected call of CheckCredentialModels.
func (mr *MockAPIMockRecorder) CheckCredentialModels(arg0, arg1 any) *MockAPICheckCredentialModelsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCredentialModels", reflect.TypeOf((*MockAPI)(nil).CheckCredentialModels), arg0, arg1)
	return &MockAPICheckCredentialModelsCall{Call: call}
}

// MockAPICheckCredentialModelsCall wrap *gomock.Call
type MockAPICheckCredentialModelsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPICheckCredentialModelsCall) Return(arg0 []params.UpdateCredentialModelResult, arg1 error) *MockAPICheckCredentialModelsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPICheckCredentialModelsCall) Do(f func(context.Context, params.TaggedCredential) ([]params.UpdateCredentialModelResult, error)) *MockAPICheckCredentialModelsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPICheckCredentialModelsCall) DoAndReturn(f func(context.Context, params.TaggedCredential) ([]params.UpdateCredentialModelResult, error)) *MockAPICheckCredentialModelsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CheckMachines mocks base method.
func (m *MockAPI) CheckMachines(modelUUID string) ([]error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckMachines", modelUUID)
	ret0, _ := ret[0].([]error)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckMachines indicates an expected call of CheckMachines.
func (mr *MockAPIMockRecorder) CheckMachines(modelUUID any) *MockAPICheckMachinesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckMachines", reflect.TypeOf((*MockAPI)(nil).CheckMachines), modelUUID)
	return &MockAPICheckMachinesCall{Call: call}
}

// MockAPICheckMachinesCall wrap *gomock.Call
type MockAPICheckMachinesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPICheckMachinesCall) Return(arg0 []error, arg1 error) *MockAPICheckMachinesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPICheckMachinesCall) Do(f func(string) ([]error, error)) *MockAPICheckMachinesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPICheckMachinesCall) DoAndReturn(f func(string) ([]error, error)) *MockAPICheckMachinesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Close mocks base method.
func (m *MockAPI) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockAPIMockRecorder) Close() *MockAPICloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAPI)(nil).Close))
	return &MockAPICloseCall{Call: call}
}

// MockAPICloseCall wrap *gomock.Call
type MockAPICloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPICloseCall) Return(arg0 error) *MockAPICloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPICloseCall) Do(f func() error) *MockAPICloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPICloseCall) DoAndReturn(f func() error) *MockAPICloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Cloud mocks base method.
func (m *MockAPI) Cloud(arg0 names.CloudTag, arg1 *cloud.Cloud) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cloud", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cloud indicates an expected call of Cloud.
func (mr *MockAPIMockRecorder) Cloud(arg0, arg1 any) *MockAPICloudCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cloud", reflect.TypeOf((*MockAPI)(nil).Cloud), arg0, arg1)
	return &MockAPICloudCall{Call: call}
}

// MockAPICloudCall wrap *gomock.Call
type MockAPICloudCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPICloudCall) Return(arg0 error) *MockAPICloudCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPICloudCall) Do(f func(names.CloudTag, *cloud.Cloud) error) *MockAPICloudCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPICloudCall) DoAndReturn(f func(names.CloudTag, *cloud.Cloud) error) *MockAPICloudCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Clouds mocks base method.
func (m *MockAPI) Clouds() (map[names.CloudTag]cloud.Cloud, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clouds")
	ret0, _ := ret[0].(map[names.CloudTag]cloud.Cloud)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clouds indicates an expected call of Clouds.
func (mr *MockAPIMockRecorder) Clouds() *MockAPICloudsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clouds", reflect.TypeOf((*MockAPI)(nil).Clouds))
	return &MockAPICloudsCall{Call: call}
}

// MockAPICloudsCall wrap *gomock.Call
type MockAPICloudsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPICloudsCall) Return(arg0 map[names.CloudTag]cloud.Cloud, arg1 error) *MockAPICloudsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPICloudsCall) Do(f func() (map[names.CloudTag]cloud.Cloud, error)) *MockAPICloudsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPICloudsCall) DoAndReturn(f func() (map[names.CloudTag]cloud.Cloud, error)) *MockAPICloudsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ConnectControllerStream mocks base method.
func (m *MockAPI) ConnectControllerStream(path string, attrs url.Values, headers http.Header) (base.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectControllerStream", path, attrs, headers)
	ret0, _ := ret[0].(base.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConnectControllerStream indicates an expected call of ConnectControllerStream.
func (mr *MockAPIMockRecorder) ConnectControllerStream(path, attrs, headers any) *MockAPIConnectControllerStreamCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectControllerStream", reflect.TypeOf((*MockAPI)(nil).ConnectControllerStream), path, attrs, headers)
	return &MockAPIConnectControllerStreamCall{Call: call}
}

// MockAPIConnectControllerStreamCall wrap *gomock.Call
type MockAPIConnectControllerStreamCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIConnectControllerStreamCall) Return(arg0 base.Stream, arg1 error) *MockAPIConnectControllerStreamCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIConnectControllerStreamCall) Do(f func(string, url.Values, http.Header) (base.Stream, error)) *MockAPIConnectControllerStreamCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIConnectControllerStreamCall) DoAndReturn(f func(string, url.Values, http.Header) (base.Stream, error)) *MockAPIConnectControllerStreamCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ConnectStream mocks base method.
func (m *MockAPI) ConnectStream(arg0 string, arg1 url.Values) (base.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectStream", arg0, arg1)
	ret0, _ := ret[0].(base.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConnectStream indicates an expected call of ConnectStream.
func (mr *MockAPIMockRecorder) ConnectStream(arg0, arg1 any) *MockAPIConnectStreamCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectStream", reflect.TypeOf((*MockAPI)(nil).ConnectStream), arg0, arg1)
	return &MockAPIConnectStreamCall{Call: call}
}

// MockAPIConnectStreamCall wrap *gomock.Call
type MockAPIConnectStreamCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIConnectStreamCall) Return(arg0 base.Stream, arg1 error) *MockAPIConnectStreamCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIConnectStreamCall) Do(f func(string, url.Values) (base.Stream, error)) *MockAPIConnectStreamCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIConnectStreamCall) DoAndReturn(f func(string, url.Values) (base.Stream, error)) *MockAPIConnectStreamCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Context mocks base method.
func (m *MockAPI) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockAPIMockRecorder) Context() *MockAPIContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockAPI)(nil).Context))
	return &MockAPIContextCall{Call: call}
}

// MockAPIContextCall wrap *gomock.Call
type MockAPIContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIContextCall) Return(arg0 context.Context) *MockAPIContextCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIContextCall) Do(f func() context.Context) *MockAPIContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIContextCall) DoAndReturn(f func() context.Context) *MockAPIContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ControllerConfig mocks base method.
func (m *MockAPI) ControllerConfig(arg0 context.Context) (params.ControllerConfigResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ControllerConfig", arg0)
	ret0, _ := ret[0].(params.ControllerConfigResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ControllerConfig indicates an expected call of ControllerConfig.
func (mr *MockAPIMockRecorder) ControllerConfig(arg0 any) *MockAPIControllerConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ControllerConfig", reflect.TypeOf((*MockAPI)(nil).ControllerConfig), arg0)
	return &MockAPIControllerConfigCall{Call: call}
}

// MockAPIControllerConfigCall wrap *gomock.Call
type MockAPIControllerConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIControllerConfigCall) Return(arg0 params.ControllerConfigResult, arg1 error) *MockAPIControllerConfigCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIControllerConfigCall) Do(f func(context.Context) (params.ControllerConfigResult, error)) *MockAPIControllerConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIControllerConfigCall) DoAndReturn(f func(context.Context) (params.ControllerConfigResult, error)) *MockAPIControllerConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ControllerModelSummary mocks base method.
func (m *MockAPI) ControllerModelSummary(arg0 context.Context, arg1 *params.ModelSummary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ControllerModelSummary", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ControllerModelSummary indicates an expected call of ControllerModelSummary.
func (mr *MockAPIMockRecorder) ControllerModelSummary(arg0, arg1 any) *MockAPIControllerModelSummaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ControllerModelSummary", reflect.TypeOf((*MockAPI)(nil).ControllerModelSummary), arg0, arg1)
	return &MockAPIControllerModelSummaryCall{Call: call}
}

// MockAPIControllerModelSummaryCall wrap *gomock.Call
type MockAPIControllerModelSummaryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIControllerModelSummaryCall) Return(arg0 error) *MockAPIControllerModelSummaryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIControllerModelSummaryCall) Do(f func(context.Context, *params.ModelSummary) error) *MockAPIControllerModelSummaryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIControllerModelSummaryCall) DoAndReturn(f func(context.Context, *params.ModelSummary) error) *MockAPIControllerModelSummaryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateModel mocks base method.
func (m *MockAPI) CreateModel(arg0 context.Context, arg1 *params.ModelCreateArgs, arg2 *params.ModelInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModel", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateModel indicates an expected call of CreateModel.
func (mr *MockAPIMockRecorder) CreateModel(arg0, arg1, arg2 any) *MockAPICreateModelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModel", reflect.TypeOf((*MockAPI)(nil).CreateModel), arg0, arg1, arg2)
	return &MockAPICreateModelCall{Call: call}
}

// MockAPICreateModelCall wrap *gomock.Call
type MockAPICreateModelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPICreateModelCall) Return(arg0 error) *MockAPICreateModelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPICreateModelCall) Do(f func(context.Context, *params.ModelCreateArgs, *params.ModelInfo) error) *MockAPICreateModelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPICreateModelCall) DoAndReturn(f func(context.Context, *params.ModelCreateArgs, *params.ModelInfo) error) *MockAPICreateModelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CredentialContents mocks base method.
func (m *MockAPI) CredentialContents(arg0, credential string, withSecrets bool) ([]params.CredentialContentResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CredentialContents", arg0, credential, withSecrets)
	ret0, _ := ret[0].([]params.CredentialContentResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CredentialContents indicates an expected call of CredentialContents.
func (mr *MockAPIMockRecorder) CredentialContents(arg0, credential, withSecrets any) *MockAPICredentialContentsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CredentialContents", reflect.TypeOf((*MockAPI)(nil).CredentialContents), arg0, credential, withSecrets)
	return &MockAPICredentialContentsCall{Call: call}
}

// MockAPICredentialContentsCall wrap *gomock.Call
type MockAPICredentialContentsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPICredentialContentsCall) Return(arg0 []params.CredentialContentResult, arg1 error) *MockAPICredentialContentsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPICredentialContentsCall) Do(f func(string, string, bool) ([]params.CredentialContentResult, error)) *MockAPICredentialContentsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPICredentialContentsCall) DoAndReturn(f func(string, string, bool) ([]params.CredentialContentResult, error)) *MockAPICredentialContentsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DestroyApplicationOffer mocks base method.
func (m *MockAPI) DestroyApplicationOffer(arg0 context.Context, arg1 string, arg2 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyApplicationOffer", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyApplicationOffer indicates an expected call of DestroyApplicationOffer.
func (mr *MockAPIMockRecorder) DestroyApplicationOffer(arg0, arg1, arg2 any) *MockAPIDestroyApplicationOfferCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyApplicationOffer", reflect.TypeOf((*MockAPI)(nil).DestroyApplicationOffer), arg0, arg1, arg2)
	return &MockAPIDestroyApplicationOfferCall{Call: call}
}

// MockAPIDestroyApplicationOfferCall wrap *gomock.Call
type MockAPIDestroyApplicationOfferCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIDestroyApplicationOfferCall) Return(arg0 error) *MockAPIDestroyApplicationOfferCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIDestroyApplicationOfferCall) Do(f func(context.Context, string, bool) error) *MockAPIDestroyApplicationOfferCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIDestroyApplicationOfferCall) DoAndReturn(f func(context.Context, string, bool) error) *MockAPIDestroyApplicationOfferCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DestroyModel mocks base method.
func (m *MockAPI) DestroyModel(arg0 context.Context, arg1 names.ModelTag, arg2, arg3 *bool, arg4, arg5 *time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyModel", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyModel indicates an expected call of DestroyModel.
func (mr *MockAPIMockRecorder) DestroyModel(arg0, arg1, arg2, arg3, arg4, arg5 any) *MockAPIDestroyModelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyModel", reflect.TypeOf((*MockAPI)(nil).DestroyModel), arg0, arg1, arg2, arg3, arg4, arg5)
	return &MockAPIDestroyModelCall{Call: call}
}

// MockAPIDestroyModelCall wrap *gomock.Call
type MockAPIDestroyModelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIDestroyModelCall) Return(arg0 error) *MockAPIDestroyModelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIDestroyModelCall) Do(f func(context.Context, names.ModelTag, *bool, *bool, *time.Duration, *time.Duration) error) *MockAPIDestroyModelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIDestroyModelCall) DoAndReturn(f func(context.Context, names.ModelTag, *bool, *bool, *time.Duration, *time.Duration) error) *MockAPIDestroyModelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DumpModel mocks base method.
func (m *MockAPI) DumpModel(arg0 context.Context, arg1 names.ModelTag, arg2 bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DumpModel", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DumpModel indicates an expected call of DumpModel.
func (mr *MockAPIMockRecorder) DumpModel(arg0, arg1, arg2 any) *MockAPIDumpModelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DumpModel", reflect.TypeOf((*MockAPI)(nil).DumpModel), arg0, arg1, arg2)
	return &MockAPIDumpModelCall{Call: call}
}

// MockAPIDumpModelCall wrap *gomock.Call
type MockAPIDumpModelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIDumpModelCall) Return(arg0 string, arg1 error) *MockAPIDumpModelCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIDumpModelCall) Do(f func(context.Context, names.ModelTag, bool) (string, error)) *MockAPIDumpModelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIDumpModelCall) DoAndReturn(f func(context.Context, names.ModelTag, bool) (string, error)) *MockAPIDumpModelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DumpModelDB mocks base method.
func (m *MockAPI) DumpModelDB(arg0 context.Context, arg1 names.ModelTag) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DumpModelDB", arg0, arg1)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DumpModelDB indicates an expected call of DumpModelDB.
func (mr *MockAPIMockRecorder) DumpModelDB(arg0, arg1 any) *MockAPIDumpModelDBCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DumpModelDB", reflect.TypeOf((*MockAPI)(nil).DumpModelDB), arg0, arg1)
	return &MockAPIDumpModelDBCall{Call: call}
}

// MockAPIDumpModelDBCall wrap *gomock.Call
type MockAPIDumpModelDBCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIDumpModelDBCall) Return(arg0 map[string]any, arg1 error) *MockAPIDumpModelDBCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIDumpModelDBCall) Do(f func(context.Context, names.ModelTag) (map[string]any, error)) *MockAPIDumpModelDBCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIDumpModelDBCall) DoAndReturn(f func(context.Context, names.ModelTag) (map[string]any, error)) *MockAPIDumpModelDBCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindApplicationOffers mocks base method.
func (m *MockAPI) FindApplicationOffers(arg0 context.Context, arg1 []params.OfferFilter) ([]params.ApplicationOfferAdminDetailsV5, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindApplicationOffers", arg0, arg1)
	ret0, _ := ret[0].([]params.ApplicationOfferAdminDetailsV5)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindApplicationOffers indicates an expected call of FindApplicationOffers.
func (mr *MockAPIMockRecorder) FindApplicationOffers(arg0, arg1 any) *MockAPIFindApplicationOffersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindApplicationOffers", reflect.TypeOf((*MockAPI)(nil).FindApplicationOffers), arg0, arg1)
	return &MockAPIFindApplicationOffersCall{Call: call}
}

// MockAPIFindApplicationOffersCall wrap *gomock.Call
type MockAPIFindApplicationOffersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIFindApplicationOffersCall) Return(arg0 []params.ApplicationOfferAdminDetailsV5, arg1 error) *MockAPIFindApplicationOffersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIFindApplicationOffersCall) Do(f func(context.Context, []params.OfferFilter) ([]params.ApplicationOfferAdminDetailsV5, error)) *MockAPIFindApplicationOffersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIFindApplicationOffersCall) DoAndReturn(f func(context.Context, []params.OfferFilter) ([]params.ApplicationOfferAdminDetailsV5, error)) *MockAPIFindApplicationOffersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetApplicationOffer mocks base method.
func (m *MockAPI) GetApplicationOffer(arg0 context.Context, arg1 *params.ApplicationOfferAdminDetailsV5) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApplicationOffer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetApplicationOffer indicates an expected call of GetApplicationOffer.
func (mr *MockAPIMockRecorder) GetApplicationOffer(arg0, arg1 any) *MockAPIGetApplicationOfferCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApplicationOffer", reflect.TypeOf((*MockAPI)(nil).GetApplicationOffer), arg0, arg1)
	return &MockAPIGetApplicationOfferCall{Call: call}
}

// MockAPIGetApplicationOfferCall wrap *gomock.Call
type MockAPIGetApplicationOfferCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIGetApplicationOfferCall) Return(arg0 error) *MockAPIGetApplicationOfferCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIGetApplicationOfferCall) Do(f func(context.Context, *params.ApplicationOfferAdminDetailsV5) error) *MockAPIGetApplicationOfferCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIGetApplicationOfferCall) DoAndReturn(f func(context.Context, *params.ApplicationOfferAdminDetailsV5) error) *MockAPIGetApplicationOfferCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetApplicationOfferConsumeDetails mocks base method.
func (m *MockAPI) GetApplicationOfferConsumeDetails(arg0 context.Context, arg1 names.UserTag, arg2 *params.ConsumeOfferDetails, arg3 bakery.Version) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApplicationOfferConsumeDetails", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetApplicationOfferConsumeDetails indicates an expected call of GetApplicationOfferConsumeDetails.
func (mr *MockAPIMockRecorder) GetApplicationOfferConsumeDetails(arg0, arg1, arg2, arg3 any) *MockAPIGetApplicationOfferConsumeDetailsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApplicationOfferConsumeDetails", reflect.TypeOf((*MockAPI)(nil).GetApplicationOfferConsumeDetails), arg0, arg1, arg2, arg3)
	return &MockAPIGetApplicationOfferConsumeDetailsCall{Call: call}
}

// MockAPIGetApplicationOfferConsumeDetailsCall wrap *gomock.Call
type MockAPIGetApplicationOfferConsumeDetailsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIGetApplicationOfferConsumeDetailsCall) Return(arg0 error) *MockAPIGetApplicationOfferConsumeDetailsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIGetApplicationOfferConsumeDetailsCall) Do(f func(context.Context, names.UserTag, *params.ConsumeOfferDetails, bakery.Version) error) *MockAPIGetApplicationOfferConsumeDetailsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIGetApplicationOfferConsumeDetailsCall) DoAndReturn(f func(context.Context, names.UserTag, *params.ConsumeOfferDetails, bakery.Version) error) *MockAPIGetApplicationOfferConsumeDetailsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GrantApplicationOfferAccess mocks base method.
func (m *MockAPI) GrantApplicationOfferAccess(arg0 context.Context, arg1 string, arg2 names.UserTag, arg3 params.OfferAccessPermission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantApplicationOfferAccess", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// GrantApplicationOfferAccess indicates an expected call of GrantApplicationOfferAccess.
func (mr *MockAPIMockRecorder) GrantApplicationOfferAccess(arg0, arg1, arg2, arg3 any) *MockAPIGrantApplicationOfferAccessCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantApplicationOfferAccess", reflect.TypeOf((*MockAPI)(nil).GrantApplicationOfferAccess), arg0, arg1, arg2, arg3)
	return &MockAPIGrantApplicationOfferAccessCall{Call: call}
}

// MockAPIGrantApplicationOfferAccessCall wrap *gomock.Call
type MockAPIGrantApplicationOfferAccessCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIGrantApplicationOfferAccessCall) Return(arg0 error) *MockAPIGrantApplicationOfferAccessCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIGrantApplicationOfferAccessCall) Do(f func(context.Context, string, names.UserTag, params.OfferAccessPermission) error) *MockAPIGrantApplicationOfferAccessCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIGrantApplicationOfferAccessCall) DoAndReturn(f func(context.Context, string, names.UserTag, params.OfferAccessPermission) error) *MockAPIGrantApplicationOfferAccessCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GrantJIMMModelAdmin mocks base method.
func (m *MockAPI) GrantJIMMModelAdmin(arg0 context.Context, arg1 names.ModelTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantJIMMModelAdmin", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GrantJIMMModelAdmin indicates an expected call of GrantJIMMModelAdmin.
func (mr *MockAPIMockRecorder) GrantJIMMModelAdmin(arg0, arg1 any) *MockAPIGrantJIMMModelAdminCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantJIMMModelAdmin", reflect.TypeOf((*MockAPI)(nil).GrantJIMMModelAdmin), arg0, arg1)
	return &MockAPIGrantJIMMModelAdminCall{Call: call}
}

// MockAPIGrantJIMMModelAdminCall wrap *gomock.Call
type MockAPIGrantJIMMModelAdminCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIGrantJIMMModelAdminCall) Return(arg0 error) *MockAPIGrantJIMMModelAdminCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIGrantJIMMModelAdminCall) Do(f func(context.Context, names.ModelTag) error) *MockAPIGrantJIMMModelAdminCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIGrantJIMMModelAdminCall) DoAndReturn(f func(context.Context, names.ModelTag) error) *MockAPIGrantJIMMModelAdminCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GrantModelAccess mocks base method.
func (m *MockAPI) GrantModelAccess(arg0 context.Context, arg1 names.ModelTag, arg2 names.UserTag, arg3 params.UserAccessPermission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantModelAccess", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// GrantModelAccess indicates an expected call of GrantModelAccess.
func (mr *MockAPIMockRecorder) GrantModelAccess(arg0, arg1, arg2, arg3 any) *MockAPIGrantModelAccessCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantModelAccess", reflect.TypeOf((*MockAPI)(nil).GrantModelAccess), arg0, arg1, arg2, arg3)
	return &MockAPIGrantModelAccessCall{Call: call}
}

// MockAPIGrantModelAccessCall wrap *gomock.Call
type MockAPIGrantModelAccessCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIGrantModelAccessCall) Return(arg0 error) *MockAPIGrantModelAccessCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIGrantModelAccessCall) Do(f func(context.Context, names.ModelTag, names.UserTag, params.UserAccessPermission) error) *MockAPIGrantModelAccessCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIGrantModelAccessCall) DoAndReturn(f func(context.Context, names.ModelTag, names.UserTag, params.UserAccessPermission) error) *MockAPIGrantModelAccessCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HTTPClient mocks base method.
func (m *MockAPI) HTTPClient() (*httprequest.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTTPClient")
	ret0, _ := ret[0].(*httprequest.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HTTPClient indicates an expected call of HTTPClient.
func (mr *MockAPIMockRecorder) HTTPClient() *MockAPIHTTPClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTTPClient", reflect.TypeOf((*MockAPI)(nil).HTTPClient))
	return &MockAPIHTTPClientCall{Call: call}
}

// MockAPIHTTPClientCall wrap *gomock.Call
type MockAPIHTTPClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIHTTPClientCall) Return(arg0 *httprequest.Client, arg1 error) *MockAPIHTTPClientCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIHTTPClientCall) Do(f func() (*httprequest.Client, error)) *MockAPIHTTPClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIHTTPClientCall) DoAndReturn(f func() (*httprequest.Client, error)) *MockAPIHTTPClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Import mocks base method.
func (m *MockAPI) Import(bytes []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Import", bytes)
	ret0, _ := ret[0].(error)
	return ret0
}

// Import indicates an expected call of Import.
func (mr *MockAPIMockRecorder) Import(bytes any) *MockAPIImportCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Import", reflect.TypeOf((*MockAPI)(nil).Import), bytes)
	return &MockAPIImportCall{Call: call}
}

// MockAPIImportCall wrap *gomock.Call
type MockAPIImportCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIImportCall) Return(arg0 error) *MockAPIImportCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIImportCall) Do(f func([]byte) error) *MockAPIImportCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIImportCall) DoAndReturn(f func([]byte) error) *MockAPIImportCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsBroken mocks base method.
func (m *MockAPI) IsBroken() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBroken")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBroken indicates an expected call of IsBroken.
func (mr *MockAPIMockRecorder) IsBroken() *MockAPIIsBrokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBroken", reflect.TypeOf((*MockAPI)(nil).IsBroken))
	return &MockAPIIsBrokenCall{Call: call}
}

// MockAPIIsBrokenCall wrap *gomock.Call
type MockAPIIsBrokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIIsBrokenCall) Return(arg0 bool) *MockAPIIsBrokenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIIsBrokenCall) Do(f func() bool) *MockAPIIsBrokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIIsBrokenCall) DoAndReturn(f func() bool) *MockAPIIsBrokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LatestLogTime mocks base method.
func (m *MockAPI) LatestLogTime(arg0 string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestLogTime", arg0)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestLogTime indicates an expected call of LatestLogTime.
func (mr *MockAPIMockRecorder) LatestLogTime(arg0 any) *MockAPILatestLogTimeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestLogTime", reflect.TypeOf((*MockAPI)(nil).LatestLogTime), arg0)
	return &MockAPILatestLogTimeCall{Call: call}
}

// MockAPILatestLogTimeCall wrap *gomock.Call
type MockAPILatestLogTimeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPILatestLogTimeCall) Return(arg0 time.Time, arg1 error) *MockAPILatestLogTimeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPILatestLogTimeCall) Do(f func(string) (time.Time, error)) *MockAPILatestLogTimeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPILatestLogTimeCall) DoAndReturn(f func(string) (time.Time, error)) *MockAPILatestLogTimeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListApplicationOffers mocks base method.
func (m *MockAPI) ListApplicationOffers(arg0 context.Context, arg1 []params.OfferFilter) ([]params.ApplicationOfferAdminDetailsV5, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApplicationOffers", arg0, arg1)
	ret0, _ := ret[0].([]params.ApplicationOfferAdminDetailsV5)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApplicationOffers indicates an expected call of ListApplicationOffers.
func (mr *MockAPIMockRecorder) ListApplicationOffers(arg0, arg1 any) *MockAPIListApplicationOffersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApplicationOffers", reflect.TypeOf((*MockAPI)(nil).ListApplicationOffers), arg0, arg1)
	return &MockAPIListApplicationOffersCall{Call: call}
}

// MockAPIListApplicationOffersCall wrap *gomock.Call
type MockAPIListApplicationOffersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIListApplicationOffersCall) Return(arg0 []params.ApplicationOfferAdminDetailsV5, arg1 error) *MockAPIListApplicationOffersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIListApplicationOffersCall) Do(f func(context.Context, []params.OfferFilter) ([]params.ApplicationOfferAdminDetailsV5, error)) *MockAPIListApplicationOffersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIListApplicationOffersCall) DoAndReturn(f func(context.Context, []params.OfferFilter) ([]params.ApplicationOfferAdminDetailsV5, error)) *MockAPIListApplicationOffersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListFilesystems mocks base method.
func (m *MockAPI) ListFilesystems(ctx context.Context, machines []string) ([]params.FilesystemDetailsListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFilesystems", ctx, machines)
	ret0, _ := ret[0].([]params.FilesystemDetailsListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFilesystems indicates an expected call of ListFilesystems.
func (mr *MockAPIMockRecorder) ListFilesystems(ctx, machines any) *MockAPIListFilesystemsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFilesystems", reflect.TypeOf((*MockAPI)(nil).ListFilesystems), ctx, machines)
	return &MockAPIListFilesystemsCall{Call: call}
}

// MockAPIListFilesystemsCall wrap *gomock.Call
type MockAPIListFilesystemsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIListFilesystemsCall) Return(arg0 []params.FilesystemDetailsListResult, arg1 error) *MockAPIListFilesystemsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIListFilesystemsCall) Do(f func(context.Context, []string) ([]params.FilesystemDetailsListResult, error)) *MockAPIListFilesystemsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIListFilesystemsCall) DoAndReturn(f func(context.Context, []string) ([]params.FilesystemDetailsListResult, error)) *MockAPIListFilesystemsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListModelSummaries mocks base method.
func (m *MockAPI) ListModelSummaries(arg0 context.Context, arg1 params.ModelSummariesRequest) (params.ModelSummaryResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModelSummaries", arg0, arg1)
	ret0, _ := ret[0].(params.ModelSummaryResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModelSummaries indicates an expected call of ListModelSummaries.
func (mr *MockAPIMockRecorder) ListModelSummaries(arg0, arg1 any) *MockAPIListModelSummariesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModelSummaries", reflect.TypeOf((*MockAPI)(nil).ListModelSummaries), arg0, arg1)
	return &MockAPIListModelSummariesCall{Call: call}
}

// MockAPIListModelSummariesCall wrap *gomock.Call
type MockAPIListModelSummariesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIListModelSummariesCall) Return(arg0 params.ModelSummaryResults, arg1 error) *MockAPIListModelSummariesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIListModelSummariesCall) Do(f func(context.Context, params.ModelSummariesRequest) (params.ModelSummaryResults, error)) *MockAPIListModelSummariesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIListModelSummariesCall) DoAndReturn(f func(context.Context, params.ModelSummariesRequest) (params.ModelSummaryResults, error)) *MockAPIListModelSummariesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListModels mocks base method.
func (m *MockAPI) ListModels(ctx context.Context) ([]base.UserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModels", ctx)
	ret0, _ := ret[0].([]base.UserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModels indicates an expected call of ListModels.
func (mr *MockAPIMockRecorder) ListModels(ctx any) *MockAPIListModelsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModels", reflect.TypeOf((*MockAPI)(nil).ListModels), ctx)
	return &MockAPIListModelsCall{Call: call}
}

// MockAPIListModelsCall wrap *gomock.Call
type MockAPIListModelsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIListModelsCall) Return(arg0 []base.UserModel, arg1 error) *MockAPIListModelsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIListModelsCall) Do(f func(context.Context) ([]base.UserModel, error)) *MockAPIListModelsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIListModelsCall) DoAndReturn(f func(context.Context) ([]base.UserModel, error)) *MockAPIListModelsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListStorageDetails mocks base method.
func (m *MockAPI) ListStorageDetails(ctx context.Context) ([]params.StorageDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStorageDetails", ctx)
	ret0, _ := ret[0].([]params.StorageDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStorageDetails indicates an expected call of ListStorageDetails.
func (mr *MockAPIMockRecorder) ListStorageDetails(ctx any) *MockAPIListStorageDetailsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStorageDetails", reflect.TypeOf((*MockAPI)(nil).ListStorageDetails), ctx)
	return &MockAPIListStorageDetailsCall{Call: call}
}

// MockAPIListStorageDetailsCall wrap *gomock.Call
type MockAPIListStorageDetailsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIListStorageDetailsCall) Return(arg0 []params.StorageDetails, arg1 error) *MockAPIListStorageDetailsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIListStorageDetailsCall) Do(f func(context.Context) ([]params.StorageDetails, error)) *MockAPIListStorageDetailsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIListStorageDetailsCall) DoAndReturn(f func(context.Context) ([]params.StorageDetails, error)) *MockAPIListStorageDetailsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListVolumes mocks base method.
func (m *MockAPI) ListVolumes(ctx context.Context, machines []string) ([]params.VolumeDetailsListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVolumes", ctx, machines)
	ret0, _ := ret[0].([]params.VolumeDetailsListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVolumes indicates an expected call of ListVolumes.
func (mr *MockAPIMockRecorder) ListVolumes(ctx, machines any) *MockAPIListVolumesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVolumes", reflect.TypeOf((*MockAPI)(nil).ListVolumes), ctx, machines)
	return &MockAPIListVolumesCall{Call: call}
}

// MockAPIListVolumesCall wrap *gomock.Call
type MockAPIListVolumesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIListVolumesCall) Return(arg0 []params.VolumeDetailsListResult, arg1 error) *MockAPIListVolumesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIListVolumesCall) Do(f func(context.Context, []string) ([]params.VolumeDetailsListResult, error)) *MockAPIListVolumesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIListVolumesCall) DoAndReturn(f func(context.Context, []string) ([]params.VolumeDetailsListResult, error)) *MockAPIListVolumesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ModelInfo mocks base method.
func (m *MockAPI) ModelInfo(arg0 context.Context, arg1 *params.ModelInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelInfo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModelInfo indicates an expected call of ModelInfo.
func (mr *MockAPIMockRecorder) ModelInfo(arg0, arg1 any) *MockAPIModelInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelInfo", reflect.TypeOf((*MockAPI)(nil).ModelInfo), arg0, arg1)
	return &MockAPIModelInfoCall{Call: call}
}

// MockAPIModelInfoCall wrap *gomock.Call
type MockAPIModelInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIModelInfoCall) Return(arg0 error) *MockAPIModelInfoCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIModelInfoCall) Do(f func(context.Context, *params.ModelInfo) error) *MockAPIModelInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIModelInfoCall) DoAndReturn(f func(context.Context, *params.ModelInfo) error) *MockAPIModelInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ModelStatus mocks base method.
func (m *MockAPI) ModelStatus(arg0 context.Context, arg1 *params.ModelStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelStatus", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModelStatus indicates an expected call of ModelStatus.
func (mr *MockAPIMockRecorder) ModelStatus(arg0, arg1 any) *MockAPIModelStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelStatus", reflect.TypeOf((*MockAPI)(nil).ModelStatus), arg0, arg1)
	return &MockAPIModelStatusCall{Call: call}
}

// MockAPIModelStatusCall wrap *gomock.Call
type MockAPIModelStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIModelStatusCall) Return(arg0 error) *MockAPIModelStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIModelStatusCall) Do(f func(context.Context, *params.ModelStatus) error) *MockAPIModelStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIModelStatusCall) DoAndReturn(f func(context.Context, *params.ModelStatus) error) *MockAPIModelStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ModelSummaryWatcherNext mocks base method.
func (m *MockAPI) ModelSummaryWatcherNext(arg0 context.Context, arg1 string) ([]params.ModelAbstract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelSummaryWatcherNext", arg0, arg1)
	ret0, _ := ret[0].([]params.ModelAbstract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelSummaryWatcherNext indicates an expected call of ModelSummaryWatcherNext.
func (mr *MockAPIMockRecorder) ModelSummaryWatcherNext(arg0, arg1 any) *MockAPIModelSummaryWatcherNextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelSummaryWatcherNext", reflect.TypeOf((*MockAPI)(nil).ModelSummaryWatcherNext), arg0, arg1)
	return &MockAPIModelSummaryWatcherNextCall{Call: call}
}

// MockAPIModelSummaryWatcherNextCall wrap *gomock.Call
type MockAPIModelSummaryWatcherNextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIModelSummaryWatcherNextCall) Return(arg0 []params.ModelAbstract, arg1 error) *MockAPIModelSummaryWatcherNextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIModelSummaryWatcherNextCall) Do(f func(context.Context, string) ([]params.ModelAbstract, error)) *MockAPIModelSummaryWatcherNextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIModelSummaryWatcherNextCall) DoAndReturn(f func(context.Context, string) ([]params.ModelAbstract, error)) *MockAPIModelSummaryWatcherNextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ModelSummaryWatcherStop mocks base method.
func (m *MockAPI) ModelSummaryWatcherStop(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelSummaryWatcherStop", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModelSummaryWatcherStop indicates an expected call of ModelSummaryWatcherStop.
func (mr *MockAPIMockRecorder) ModelSummaryWatcherStop(arg0, arg1 any) *MockAPIModelSummaryWatcherStopCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelSummaryWatcherStop", reflect.TypeOf((*MockAPI)(nil).ModelSummaryWatcherStop), arg0, arg1)
	return &MockAPIModelSummaryWatcherStopCall{Call: call}
}

// MockAPIModelSummaryWatcherStopCall wrap *gomock.Call
type MockAPIModelSummaryWatcherStopCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIModelSummaryWatcherStopCall) Return(arg0 error) *MockAPIModelSummaryWatcherStopCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIModelSummaryWatcherStopCall) Do(f func(context.Context, string) error) *MockAPIModelSummaryWatcherStopCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIModelSummaryWatcherStopCall) DoAndReturn(f func(context.Context, string) error) *MockAPIModelSummaryWatcherStopCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ModelTag mocks base method.
func (m *MockAPI) ModelTag() (names.ModelTag, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelTag")
	ret0, _ := ret[0].(names.ModelTag)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ModelTag indicates an expected call of ModelTag.
func (mr *MockAPIMockRecorder) ModelTag() *MockAPIModelTagCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelTag", reflect.TypeOf((*MockAPI)(nil).ModelTag))
	return &MockAPIModelTagCall{Call: call}
}

// MockAPIModelTagCall wrap *gomock.Call
type MockAPIModelTagCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIModelTagCall) Return(arg0 names.ModelTag, arg1 bool) *MockAPIModelTagCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIModelTagCall) Do(f func() (names.ModelTag, bool)) *MockAPIModelTagCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIModelTagCall) DoAndReturn(f func() (names.ModelTag, bool)) *MockAPIModelTagCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Offer mocks base method.
func (m *MockAPI) Offer(arg0 context.Context, arg1 crossmodel.OfferURL, arg2 params.AddApplicationOffer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Offer", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Offer indicates an expected call of Offer.
func (mr *MockAPIMockRecorder) Offer(arg0, arg1, arg2 any) *MockAPIOfferCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Offer", reflect.TypeOf((*MockAPI)(nil).Offer), arg0, arg1, arg2)
	return &MockAPIOfferCall{Call: call}
}

// MockAPIOfferCall wrap *gomock.Call
type MockAPIOfferCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIOfferCall) Return(arg0 error) *MockAPIOfferCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIOfferCall) Do(f func(context.Context, crossmodel.OfferURL, params.AddApplicationOffer) error) *MockAPIOfferCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIOfferCall) DoAndReturn(f func(context.Context, crossmodel.OfferURL, params.AddApplicationOffer) error) *MockAPIOfferCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Ping mocks base method.
func (m *MockAPI) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockAPIMockRecorder) Ping(arg0 any) *MockAPIPingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockAPI)(nil).Ping), arg0)
	return &MockAPIPingCall{Call: call}
}

// MockAPIPingCall wrap *gomock.Call
type MockAPIPingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIPingCall) Return(arg0 error) *MockAPIPingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIPingCall) Do(f func(context.Context) error) *MockAPIPingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIPingCall) DoAndReturn(f func(context.Context) error) *MockAPIPingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Prechecks mocks base method.
func (m *MockAPI) Prechecks(model migration.ModelInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prechecks", model)
	ret0, _ := ret[0].(error)
	return ret0
}

// Prechecks indicates an expected call of Prechecks.
func (mr *MockAPIMockRecorder) Prechecks(model any) *MockAPIPrechecksCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prechecks", reflect.TypeOf((*MockAPI)(nil).Prechecks), model)
	return &MockAPIPrechecksCall{Call: call}
}

// MockAPIPrechecksCall wrap *gomock.Call
type MockAPIPrechecksCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIPrechecksCall) Return(arg0 error) *MockAPIPrechecksCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIPrechecksCall) Do(f func(migration.ModelInfo) error) *MockAPIPrechecksCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIPrechecksCall) DoAndReturn(f func(migration.ModelInfo) error) *MockAPIPrechecksCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveCloud mocks base method.
func (m *MockAPI) RemoveCloud(arg0 names.CloudTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCloud", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCloud indicates an expected call of RemoveCloud.
func (mr *MockAPIMockRecorder) RemoveCloud(arg0 any) *MockAPIRemoveCloudCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCloud", reflect.TypeOf((*MockAPI)(nil).RemoveCloud), arg0)
	return &MockAPIRemoveCloudCall{Call: call}
}

// MockAPIRemoveCloudCall wrap *gomock.Call
type MockAPIRemoveCloudCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIRemoveCloudCall) Return(arg0 error) *MockAPIRemoveCloudCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIRemoveCloudCall) Do(f func(names.CloudTag) error) *MockAPIRemoveCloudCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIRemoveCloudCall) DoAndReturn(f func(names.CloudTag) error) *MockAPIRemoveCloudCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RevokeApplicationOfferAccess mocks base method.
func (m *MockAPI) RevokeApplicationOfferAccess(arg0 context.Context, arg1 string, arg2 names.UserTag, arg3 params.OfferAccessPermission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeApplicationOfferAccess", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeApplicationOfferAccess indicates an expected call of RevokeApplicationOfferAccess.
func (mr *MockAPIMockRecorder) RevokeApplicationOfferAccess(arg0, arg1, arg2, arg3 any) *MockAPIRevokeApplicationOfferAccessCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeApplicationOfferAccess", reflect.TypeOf((*MockAPI)(nil).RevokeApplicationOfferAccess), arg0, arg1, arg2, arg3)
	return &MockAPIRevokeApplicationOfferAccessCall{Call: call}
}

// MockAPIRevokeApplicationOfferAccessCall wrap *gomock.Call
type MockAPIRevokeApplicationOfferAccessCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIRevokeApplicationOfferAccessCall) Return(arg0 error) *MockAPIRevokeApplicationOfferAccessCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIRevokeApplicationOfferAccessCall) Do(f func(context.Context, string, names.UserTag, params.OfferAccessPermission) error) *MockAPIRevokeApplicationOfferAccessCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIRevokeApplicationOfferAccessCall) DoAndReturn(f func(context.Context, string, names.UserTag, params.OfferAccessPermission) error) *MockAPIRevokeApplicationOfferAccessCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RevokeCredential mocks base method.
func (m *MockAPI) RevokeCredential(arg0 context.Context, arg1 names.CloudCredentialTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeCredential", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeCredential indicates an expected call of RevokeCredential.
func (mr *MockAPIMockRecorder) RevokeCredential(arg0, arg1 any) *MockAPIRevokeCredentialCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeCredential", reflect.TypeOf((*MockAPI)(nil).RevokeCredential), arg0, arg1)
	return &MockAPIRevokeCredentialCall{Call: call}
}

// MockAPIRevokeCredentialCall wrap *gomock.Call
type MockAPIRevokeCredentialCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIRevokeCredentialCall) Return(arg0 error) *MockAPIRevokeCredentialCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIRevokeCredentialCall) Do(f func(context.Context, names.CloudCredentialTag) error) *MockAPIRevokeCredentialCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIRevokeCredentialCall) DoAndReturn(f func(context.Context, names.CloudCredentialTag) error) *MockAPIRevokeCredentialCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RevokeModelAccess mocks base method.
func (m *MockAPI) RevokeModelAccess(arg0 context.Context, arg1 names.ModelTag, arg2 names.UserTag, arg3 params.UserAccessPermission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeModelAccess", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeModelAccess indicates an expected call of RevokeModelAccess.
func (mr *MockAPIMockRecorder) RevokeModelAccess(arg0, arg1, arg2, arg3 any) *MockAPIRevokeModelAccessCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeModelAccess", reflect.TypeOf((*MockAPI)(nil).RevokeModelAccess), arg0, arg1, arg2, arg3)
	return &MockAPIRevokeModelAccessCall{Call: call}
}

// MockAPIRevokeModelAccessCall wrap *gomock.Call
type MockAPIRevokeModelAccessCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIRevokeModelAccessCall) Return(arg0 error) *MockAPIRevokeModelAccessCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIRevokeModelAccessCall) Do(f func(context.Context, names.ModelTag, names.UserTag, params.UserAccessPermission) error) *MockAPIRevokeModelAccessCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIRevokeModelAccessCall) DoAndReturn(f func(context.Context, names.ModelTag, names.UserTag, params.UserAccessPermission) error) *MockAPIRevokeModelAccessCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RootHTTPClient mocks base method.
func (m *MockAPI) RootHTTPClient() (*httprequest.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RootHTTPClient")
	ret0, _ := ret[0].(*httprequest.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RootHTTPClient indicates an expected call of RootHTTPClient.
func (mr *MockAPIMockRecorder) RootHTTPClient() *MockAPIRootHTTPClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RootHTTPClient", reflect.TypeOf((*MockAPI)(nil).RootHTTPClient))
	return &MockAPIRootHTTPClientCall{Call: call}
}

// MockAPIRootHTTPClientCall wrap *gomock.Call
type MockAPIRootHTTPClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIRootHTTPClientCall) Return(arg0 *httprequest.Client, arg1 error) *MockAPIRootHTTPClientCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIRootHTTPClientCall) Do(f func() (*httprequest.Client, error)) *MockAPIRootHTTPClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIRootHTTPClientCall) DoAndReturn(f func() (*httprequest.Client, error)) *MockAPIRootHTTPClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Status mocks base method.
func (m *MockAPI) Status(ctx context.Context, patterns []string) (*params.FullStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, patterns)
	ret0, _ := ret[0].(*params.FullStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockAPIMockRecorder) Status(ctx, patterns any) *MockAPIStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockAPI)(nil).Status), ctx, patterns)
	return &MockAPIStatusCall{Call: call}
}

// MockAPIStatusCall wrap *gomock.Call
type MockAPIStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIStatusCall) Return(arg0 *params.FullStatus, arg1 error) *MockAPIStatusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIStatusCall) Do(f func(context.Context, []string) (*params.FullStatus, error)) *MockAPIStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIStatusCall) DoAndReturn(f func(context.Context, []string) (*params.FullStatus, error)) *MockAPIStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SupportsModelSummaryWatcher mocks base method.
func (m *MockAPI) SupportsModelSummaryWatcher() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsModelSummaryWatcher")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportsModelSummaryWatcher indicates an expected call of SupportsModelSummaryWatcher.
func (mr *MockAPIMockRecorder) SupportsModelSummaryWatcher() *MockAPISupportsModelSummaryWatcherCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsModelSummaryWatcher", reflect.TypeOf((*MockAPI)(nil).SupportsModelSummaryWatcher))
	return &MockAPISupportsModelSummaryWatcherCall{Call: call}
}

// MockAPISupportsModelSummaryWatcherCall wrap *gomock.Call
type MockAPISupportsModelSummaryWatcherCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPISupportsModelSummaryWatcherCall) Return(arg0 bool) *MockAPISupportsModelSummaryWatcherCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPISupportsModelSummaryWatcherCall) Do(f func() bool) *MockAPISupportsModelSummaryWatcherCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPISupportsModelSummaryWatcherCall) DoAndReturn(f func() bool) *MockAPISupportsModelSummaryWatcherCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateCloud mocks base method.
func (m *MockAPI) UpdateCloud(arg0 names.CloudTag, arg1 cloud.Cloud) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCloud", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCloud indicates an expected call of UpdateCloud.
func (mr *MockAPIMockRecorder) UpdateCloud(arg0, arg1 any) *MockAPIUpdateCloudCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCloud", reflect.TypeOf((*MockAPI)(nil).UpdateCloud), arg0, arg1)
	return &MockAPIUpdateCloudCall{Call: call}
}

// MockAPIUpdateCloudCall wrap *gomock.Call
type MockAPIUpdateCloudCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIUpdateCloudCall) Return(arg0 error) *MockAPIUpdateCloudCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIUpdateCloudCall) Do(f func(names.CloudTag, cloud.Cloud) error) *MockAPIUpdateCloudCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIUpdateCloudCall) DoAndReturn(f func(names.CloudTag, cloud.Cloud) error) *MockAPIUpdateCloudCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateCredential mocks base method.
func (m *MockAPI) UpdateCredential(arg0 context.Context, arg1 params.TaggedCredential) ([]params.UpdateCredentialModelResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCredential", arg0, arg1)
	ret0, _ := ret[0].([]params.UpdateCredentialModelResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCredential indicates an expected call of UpdateCredential.
func (mr *MockAPIMockRecorder) UpdateCredential(arg0, arg1 any) *MockAPIUpdateCredentialCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCredential", reflect.TypeOf((*MockAPI)(nil).UpdateCredential), arg0, arg1)
	return &MockAPIUpdateCredentialCall{Call: call}
}

// MockAPIUpdateCredentialCall wrap *gomock.Call
type MockAPIUpdateCredentialCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIUpdateCredentialCall) Return(arg0 []params.UpdateCredentialModelResult, arg1 error) *MockAPIUpdateCredentialCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIUpdateCredentialCall) Do(f func(context.Context, params.TaggedCredential) ([]params.UpdateCredentialModelResult, error)) *MockAPIUpdateCredentialCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIUpdateCredentialCall) DoAndReturn(f func(context.Context, params.TaggedCredential) ([]params.UpdateCredentialModelResult, error)) *MockAPIUpdateCredentialCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpgradeModel mocks base method.
func (m *MockAPI) UpgradeModel(modelUUID string, targetVersion version.Number, stream string, ignoreAgentVersions, dryRun bool) (version.Number, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpgradeModel", modelUUID, targetVersion, stream, ignoreAgentVersions, dryRun)
	ret0, _ := ret[0].(version.Number)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpgradeModel indicates an expected call of UpgradeModel.
func (mr *MockAPIMockRecorder) UpgradeModel(modelUUID, targetVersion, stream, ignoreAgentVersions, dryRun any) *MockAPIUpgradeModelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpgradeModel", reflect.TypeOf((*MockAPI)(nil).UpgradeModel), modelUUID, targetVersion, stream, ignoreAgentVersions, dryRun)
	return &MockAPIUpgradeModelCall{Call: call}
}

// MockAPIUpgradeModelCall wrap *gomock.Call
type MockAPIUpgradeModelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIUpgradeModelCall) Return(arg0 version.Number, arg1 error) *MockAPIUpgradeModelCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIUpgradeModelCall) Do(f func(string, version.Number, string, bool, bool) (version.Number, error)) *MockAPIUpgradeModelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIUpgradeModelCall) DoAndReturn(f func(string, version.Number, string, bool, bool) (version.Number, error)) *MockAPIUpgradeModelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ValidateModelUpgrade mocks base method.
func (m *MockAPI) ValidateModelUpgrade(arg0 context.Context, arg1 names.ModelTag, arg2 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateModelUpgrade", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateModelUpgrade indicates an expected call of ValidateModelUpgrade.
func (mr *MockAPIMockRecorder) ValidateModelUpgrade(arg0, arg1, arg2 any) *MockAPIValidateModelUpgradeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateModelUpgrade", reflect.TypeOf((*MockAPI)(nil).ValidateModelUpgrade), arg0, arg1, arg2)
	return &MockAPIValidateModelUpgradeCall{Call: call}
}

// MockAPIValidateModelUpgradeCall wrap *gomock.Call
type MockAPIValidateModelUpgradeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIValidateModelUpgradeCall) Return(arg0 error) *MockAPIValidateModelUpgradeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIValidateModelUpgradeCall) Do(f func(context.Context, names.ModelTag, bool) error) *MockAPIValidateModelUpgradeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIValidateModelUpgradeCall) DoAndReturn(f func(context.Context, names.ModelTag, bool) error) *MockAPIValidateModelUpgradeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WatchAllModelSummaries mocks base method.
func (m *MockAPI) WatchAllModelSummaries(arg0 context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchAllModelSummaries", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchAllModelSummaries indicates an expected call of WatchAllModelSummaries.
func (mr *MockAPIMockRecorder) WatchAllModelSummaries(arg0 any) *MockAPIWatchAllModelSummariesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchAllModelSummaries", reflect.TypeOf((*MockAPI)(nil).WatchAllModelSummaries), arg0)
	return &MockAPIWatchAllModelSummariesCall{Call: call}
}

// MockAPIWatchAllModelSummariesCall wrap *gomock.Call
type MockAPIWatchAllModelSummariesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIWatchAllModelSummariesCall) Return(arg0 string, arg1 error) *MockAPIWatchAllModelSummariesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIWatchAllModelSummariesCall) Do(f func(context.Context) (string, error)) *MockAPIWatchAllModelSummariesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIWatchAllModelSummariesCall) DoAndReturn(f func(context.Context) (string, error)) *MockAPIWatchAllModelSummariesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
