// The code in this file was automatically generated by running httprequest-generate-client.
// DO NOT EDIT

package jemclient

import (
	"github.com/juju/httprequest"

	"github.com/CanonicalLtd/jem/params"
)

type client struct {
	Client httprequest.Client
}

// AddController adds a new controller.
func (c *client) AddController(p *params.AddController) error {
	return c.Client.Call(p, nil)
}

// AddTemplate adds a new template.
func (c *client) AddTemplate(p *params.AddTemplate) error {
	return c.Client.Call(p, nil)
}

// DeleteController removes an existing controller.
func (c *client) DeleteController(p *params.DeleteController) error {
	return c.Client.Call(p, nil)
}

// DeleteModel deletes an model from JEM.
func (c *client) DeleteModel(p *params.DeleteModel) error {
	return c.Client.Call(p, nil)
}

// DeleteTemplate deletes a template.
func (c *client) DeleteTemplate(p *params.DeleteTemplate) error {
	return c.Client.Call(p, nil)
}

// GetController returns information on a controller.
func (c *client) GetController(p *params.GetController) (*params.ControllerResponse, error) {
	var r *params.ControllerResponse
	err := c.Client.Call(p, &r)
	return r, err
}

// GetControllerPerm returns the ACL for a given controller.
// Only the owner (arg.EntityPath.User) can read the ACL.
func (c *client) GetControllerPerm(p *params.GetControllerPerm) (params.ACL, error) {
	var r params.ACL
	err := c.Client.Call(p, &r)
	return r, err
}

// GetModel returns information on a given model.
func (c *client) GetModel(p *params.GetModel) (*params.ModelResponse, error) {
	var r *params.ModelResponse
	err := c.Client.Call(p, &r)
	return r, err
}

// GetModelPerm returns the ACL for a given model.
// Only the owner (arg.EntityPath.User) can read the ACL.
func (c *client) GetModelPerm(p *params.GetModelPerm) (params.ACL, error) {
	var r params.ACL
	err := c.Client.Call(p, &r)
	return r, err
}

// GetTemplate returns information on a single template.
func (c *client) GetTemplate(p *params.GetTemplate) (*params.TemplateResponse, error) {
	var r *params.TemplateResponse
	err := c.Client.Call(p, &r)
	return r, err
}

// GetTemplatePerm returns the ACL for a given template.
// Only the owner (arg.EntityPath.User) can read the ACL.
func (c *client) GetTemplatePerm(p *params.GetTemplatePerm) (params.ACL, error) {
	var r params.ACL
	err := c.Client.Call(p, &r)
	return r, err
}

// ListController returns all the controllers stored in JEM.
// Currently the Template  and ProviderType field in each ControllerResponse is not
// populated.
func (c *client) ListController(p *params.ListController) (*params.ListControllerResponse, error) {
	var r *params.ListControllerResponse
	err := c.Client.Call(p, &r)
	return r, err
}

// ListModels returns all the models stored in JEM.
// Note that the models returned don't include the username or password.
// To gain access to a specific model, that model should be retrieved
// explicitly.
func (c *client) ListModels(p *params.ListModels) (*params.ListModelsResponse, error) {
	var r *params.ListModelsResponse
	err := c.Client.Call(p, &r)
	return r, err
}

// ListTemplates returns information on all accessible templates.
func (c *client) ListTemplates(p *params.ListTemplates) (*params.ListTemplatesResponse, error) {
	var r *params.ListTemplatesResponse
	err := c.Client.Call(p, &r)
	return r, err
}

// NewModel creates a new model inside an existing Controller.
func (c *client) NewModel(p *params.NewModel) (*params.ModelResponse, error) {
	var r *params.ModelResponse
	err := c.Client.Call(p, &r)
	return r, err
}

// SetControllerPerm sets the permissions on a controller entity.
// Only the owner (arg.EntityPath.User) can change the permissions
// on an an entity. The owner can always read an entity, even
// if it has empty ACL.
func (c *client) SetControllerPerm(p *params.SetControllerPerm) error {
	return c.Client.Call(p, nil)
}

// SetModelPerm sets the permissions on a controller entity.
// Only the owner (arg.EntityPath.User) can change the permissions
// on an an entity. The owner can always read an entity, even
// if it has empty ACL.
func (c *client) SetModelPerm(p *params.SetModelPerm) error {
	return c.Client.Call(p, nil)
}

// SetTemplatePerm sets the permissions on a template entity.
// Only the owner (arg.EntityPath.User) can change the permissions
// on an entity. The owner can always read an entity, even
// if it has an empty ACL.
func (c *client) SetTemplatePerm(p *params.SetTemplatePerm) error {
	return c.Client.Call(p, nil)
}

// WhoAmI returns authentication information on the client that is
// making the WhoAmI call.
func (c *client) WhoAmI(p *params.WhoAmI) (params.WhoAmIResponse, error) {
	var r params.WhoAmIResponse
	err := c.Client.Call(p, &r)
	return r, err
}
