// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/internal/jobtracker (interfaces: BootstrapJobStore)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/bootstrapjobstore.go -package=mocks . BootstrapJobStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	dbmodel "github.com/canonical/jimm/v3/internal/dbmodel"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBootstrapJobStore is a mock of BootstrapJobStore interface.
type MockBootstrapJobStore struct {
	ctrl     *gomock.Controller
	recorder *MockBootstrapJobStoreMockRecorder
	isgomock struct{}
}

// MockBootstrapJobStoreMockRecorder is the mock recorder for MockBootstrapJobStore.
type MockBootstrapJobStoreMockRecorder struct {
	mock *MockBootstrapJobStore
}

// NewMockBootstrapJobStore creates a new mock instance.
func NewMockBootstrapJobStore(ctrl *gomock.Controller) *MockBootstrapJobStore {
	mock := &MockBootstrapJobStore{ctrl: ctrl}
	mock.recorder = &MockBootstrapJobStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBootstrapJobStore) EXPECT() *MockBootstrapJobStoreMockRecorder {
	return m.recorder
}

// AddBootstrapLog mocks base method.
func (m *MockBootstrapJobStore) AddBootstrapLog(ctx context.Context, jobId uuid.UUID, logLine string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBootstrapLog", ctx, jobId, logLine)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBootstrapLog indicates an expected call of AddBootstrapLog.
func (mr *MockBootstrapJobStoreMockRecorder) AddBootstrapLog(ctx, jobId, logLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBootstrapLog", reflect.TypeOf((*MockBootstrapJobStore)(nil).AddBootstrapLog), ctx, jobId, logLine)
}

// GetController mocks base method.
func (m *MockBootstrapJobStore) GetController(ctx context.Context, controller *dbmodel.Controller) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetController", ctx, controller)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetController indicates an expected call of GetController.
func (mr *MockBootstrapJobStoreMockRecorder) GetController(ctx, controller any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetController", reflect.TypeOf((*MockBootstrapJobStore)(nil).GetController), ctx, controller)
}

// LockBootstrap mocks base method.
func (m *MockBootstrapJobStore) LockBootstrap(ctx context.Context, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockBootstrap", ctx, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockBootstrap indicates an expected call of LockBootstrap.
func (mr *MockBootstrapJobStoreMockRecorder) LockBootstrap(ctx, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockBootstrap", reflect.TypeOf((*MockBootstrapJobStore)(nil).LockBootstrap), ctx, ttl)
}

// UnlockBootstrap mocks base method.
func (m *MockBootstrapJobStore) UnlockBootstrap(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockBootstrap", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockBootstrap indicates an expected call of UnlockBootstrap.
func (mr *MockBootstrapJobStoreMockRecorder) UnlockBootstrap(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockBootstrap", reflect.TypeOf((*MockBootstrapJobStore)(nil).UnlockBootstrap), ctx)
}
