// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/internal/jobtracker (interfaces: BootstrapJobJujuManager)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/bootstrapjobjujumanager.go -package=mocks . BootstrapJobJujuManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dbmodel "github.com/canonical/jimm/v3/internal/dbmodel"
	juju "github.com/canonical/jimm/v3/internal/jimm/juju"
	openfga "github.com/canonical/jimm/v3/internal/openfga"
	gomock "go.uber.org/mock/gomock"
)

// MockBootstrapJobJujuManager is a mock of BootstrapJobJujuManager interface.
type MockBootstrapJobJujuManager struct {
	ctrl     *gomock.Controller
	recorder *MockBootstrapJobJujuManagerMockRecorder
	isgomock struct{}
}

// MockBootstrapJobJujuManagerMockRecorder is the mock recorder for MockBootstrapJobJujuManager.
type MockBootstrapJobJujuManagerMockRecorder struct {
	mock *MockBootstrapJobJujuManager
}

// NewMockBootstrapJobJujuManager creates a new mock instance.
func NewMockBootstrapJobJujuManager(ctrl *gomock.Controller) *MockBootstrapJobJujuManager {
	mock := &MockBootstrapJobJujuManager{ctrl: ctrl}
	mock.recorder = &MockBootstrapJobJujuManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBootstrapJobJujuManager) EXPECT() *MockBootstrapJobJujuManagerMockRecorder {
	return m.recorder
}

// AddController mocks base method.
func (m *MockBootstrapJobJujuManager) AddController(ctx context.Context, user *openfga.User, ctl *dbmodel.Controller, creds juju.ControllerCreds) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddController", ctx, user, ctl, creds)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddController indicates an expected call of AddController.
func (mr *MockBootstrapJobJujuManagerMockRecorder) AddController(ctx, user, ctl, creds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddController", reflect.TypeOf((*MockBootstrapJobJujuManager)(nil).AddController), ctx, user, ctl, creds)
}
