// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/internal/jimm/bootstrap (interfaces: BootstrapExecutor)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/bootstrapexecutor.go -package=mocks . BootstrapExecutor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	jujucommands "github.com/canonical/jimm/v3/internal/jujucommands"
	jujuclient "github.com/juju/juju/jujuclient"
	gomock "go.uber.org/mock/gomock"
)

// MockBootstrapExecutor is a mock of BootstrapExecutor interface.
type MockBootstrapExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockBootstrapExecutorMockRecorder
	isgomock struct{}
}

// MockBootstrapExecutorMockRecorder is the mock recorder for MockBootstrapExecutor.
type MockBootstrapExecutorMockRecorder struct {
	mock *MockBootstrapExecutor
}

// NewMockBootstrapExecutor creates a new mock instance.
func NewMockBootstrapExecutor(ctrl *gomock.Controller) *MockBootstrapExecutor {
	mock := &MockBootstrapExecutor{ctrl: ctrl}
	mock.recorder = &MockBootstrapExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBootstrapExecutor) EXPECT() *MockBootstrapExecutorMockRecorder {
	return m.recorder
}

// RunWrapper mocks base method.
func (m *MockBootstrapExecutor) RunWrapper(ctx context.Context, binaryPath, jujuDataDir string, params jujucommands.BootstrapCmdParams) (<-chan jujucommands.OutputLine, jujuclient.ClientStore, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunWrapper", ctx, binaryPath, jujuDataDir, params)
	ret0, _ := ret[0].(<-chan jujucommands.OutputLine)
	ret1, _ := ret[1].(jujuclient.ClientStore)
	ret2, _ := ret[2].(func())
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// RunWrapper indicates an expected call of RunWrapper.
func (mr *MockBootstrapExecutorMockRecorder) RunWrapper(ctx, binaryPath, jujuDataDir, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWrapper", reflect.TypeOf((*MockBootstrapExecutor)(nil).RunWrapper), ctx, binaryPath, jujuDataDir, params)
}
