// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/internal/jimm/bootstrap (interfaces: CredentialStore)
//
// Generated by this command:
//
//	mockgen -typed -destination=./mocks/credentialstore.go -package=mocks . CredentialStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCredentialStore is a mock of CredentialStore interface.
type MockCredentialStore struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialStoreMockRecorder
	isgomock struct{}
}

// MockCredentialStoreMockRecorder is the mock recorder for MockCredentialStore.
type MockCredentialStoreMockRecorder struct {
	mock *MockCredentialStore
}

// NewMockCredentialStore creates a new mock instance.
func NewMockCredentialStore(ctrl *gomock.Controller) *MockCredentialStore {
	mock := &MockCredentialStore{ctrl: ctrl}
	mock.recorder = &MockCredentialStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialStore) EXPECT() *MockCredentialStoreMockRecorder {
	return m.recorder
}

// GetControllerCredentials mocks base method.
func (m *MockCredentialStore) GetControllerCredentials(ctx context.Context, controllerName string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetControllerCredentials", ctx, controllerName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetControllerCredentials indicates an expected call of GetControllerCredentials.
func (mr *MockCredentialStoreMockRecorder) GetControllerCredentials(ctx, controllerName any) *MockCredentialStoreGetControllerCredentialsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetControllerCredentials", reflect.TypeOf((*MockCredentialStore)(nil).GetControllerCredentials), ctx, controllerName)
	return &MockCredentialStoreGetControllerCredentialsCall{Call: call}
}

// MockCredentialStoreGetControllerCredentialsCall wrap *gomock.Call
type MockCredentialStoreGetControllerCredentialsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCredentialStoreGetControllerCredentialsCall) Return(arg0, arg1 string, arg2 error) *MockCredentialStoreGetControllerCredentialsCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCredentialStoreGetControllerCredentialsCall) Do(f func(context.Context, string) (string, string, error)) *MockCredentialStoreGetControllerCredentialsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCredentialStoreGetControllerCredentialsCall) DoAndReturn(f func(context.Context, string) (string, string, error)) *MockCredentialStoreGetControllerCredentialsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
