// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/internal/jimm/bootstrap (interfaces: JobQueue)
//
// Generated by this command:
//
//	mockgen -typed -destination=./mocks/queue.go -package=mocks . JobQueue
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	rivertypes "github.com/canonical/jimm/v3/internal/rivertypes"
	rivertype "github.com/riverqueue/river/rivertype"
	gomock "go.uber.org/mock/gomock"
)

// MockJobQueue is a mock of JobQueue interface.
type MockJobQueue struct {
	ctrl     *gomock.Controller
	recorder *MockJobQueueMockRecorder
	isgomock struct{}
}

// MockJobQueueMockRecorder is the mock recorder for MockJobQueue.
type MockJobQueueMockRecorder struct {
	mock *MockJobQueue
}

// NewMockJobQueue creates a new mock instance.
func NewMockJobQueue(ctrl *gomock.Controller) *MockJobQueue {
	mock := &MockJobQueue{ctrl: ctrl}
	mock.recorder = &MockJobQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobQueue) EXPECT() *MockJobQueueMockRecorder {
	return m.recorder
}

// CancelJob mocks base method.
func (m *MockJobQueue) CancelJob(ctx context.Context, jobID int64) (*rivertype.JobRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelJob", ctx, jobID)
	ret0, _ := ret[0].(*rivertype.JobRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelJob indicates an expected call of CancelJob.
func (mr *MockJobQueueMockRecorder) CancelJob(ctx, jobID any) *MockJobQueueCancelJobCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelJob", reflect.TypeOf((*MockJobQueue)(nil).CancelJob), ctx, jobID)
	return &MockJobQueueCancelJobCall{Call: call}
}

// MockJobQueueCancelJobCall wrap *gomock.Call
type MockJobQueueCancelJobCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobQueueCancelJobCall) Return(arg0 *rivertype.JobRow, arg1 error) *MockJobQueueCancelJobCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobQueueCancelJobCall) Do(f func(context.Context, int64) (*rivertype.JobRow, error)) *MockJobQueueCancelJobCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobQueueCancelJobCall) DoAndReturn(f func(context.Context, int64) (*rivertype.JobRow, error)) *MockJobQueueCancelJobCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EnqueueBootstrap mocks base method.
func (m *MockJobQueue) EnqueueBootstrap(ctx context.Context, args rivertypes.BootstrapArgs) (*rivertype.JobInsertResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueBootstrap", ctx, args)
	ret0, _ := ret[0].(*rivertype.JobInsertResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnqueueBootstrap indicates an expected call of EnqueueBootstrap.
func (mr *MockJobQueueMockRecorder) EnqueueBootstrap(ctx, args any) *MockJobQueueEnqueueBootstrapCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueBootstrap", reflect.TypeOf((*MockJobQueue)(nil).EnqueueBootstrap), ctx, args)
	return &MockJobQueueEnqueueBootstrapCall{Call: call}
}

// MockJobQueueEnqueueBootstrapCall wrap *gomock.Call
type MockJobQueueEnqueueBootstrapCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobQueueEnqueueBootstrapCall) Return(arg0 *rivertype.JobInsertResult, arg1 error) *MockJobQueueEnqueueBootstrapCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobQueueEnqueueBootstrapCall) Do(f func(context.Context, rivertypes.BootstrapArgs) (*rivertype.JobInsertResult, error)) *MockJobQueueEnqueueBootstrapCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobQueueEnqueueBootstrapCall) DoAndReturn(f func(context.Context, rivertypes.BootstrapArgs) (*rivertype.JobInsertResult, error)) *MockJobQueueEnqueueBootstrapCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EnqueueDestroyController mocks base method.
func (m *MockJobQueue) EnqueueDestroyController(ctx context.Context, args rivertypes.DestroyControllerArgs) (*rivertype.JobInsertResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueDestroyController", ctx, args)
	ret0, _ := ret[0].(*rivertype.JobInsertResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnqueueDestroyController indicates an expected call of EnqueueDestroyController.
func (mr *MockJobQueueMockRecorder) EnqueueDestroyController(ctx, args any) *MockJobQueueEnqueueDestroyControllerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueDestroyController", reflect.TypeOf((*MockJobQueue)(nil).EnqueueDestroyController), ctx, args)
	return &MockJobQueueEnqueueDestroyControllerCall{Call: call}
}

// MockJobQueueEnqueueDestroyControllerCall wrap *gomock.Call
type MockJobQueueEnqueueDestroyControllerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobQueueEnqueueDestroyControllerCall) Return(arg0 *rivertype.JobInsertResult, arg1 error) *MockJobQueueEnqueueDestroyControllerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobQueueEnqueueDestroyControllerCall) Do(f func(context.Context, rivertypes.DestroyControllerArgs) (*rivertype.JobInsertResult, error)) *MockJobQueueEnqueueDestroyControllerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobQueueEnqueueDestroyControllerCall) DoAndReturn(f func(context.Context, rivertypes.DestroyControllerArgs) (*rivertype.JobInsertResult, error)) *MockJobQueueEnqueueDestroyControllerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetJobInfo mocks base method.
func (m *MockJobQueue) GetJobInfo(ctx context.Context, jobID int64) (*rivertype.JobRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobInfo", ctx, jobID)
	ret0, _ := ret[0].(*rivertype.JobRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobInfo indicates an expected call of GetJobInfo.
func (mr *MockJobQueueMockRecorder) GetJobInfo(ctx, jobID any) *MockJobQueueGetJobInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobInfo", reflect.TypeOf((*MockJobQueue)(nil).GetJobInfo), ctx, jobID)
	return &MockJobQueueGetJobInfoCall{Call: call}
}

// MockJobQueueGetJobInfoCall wrap *gomock.Call
type MockJobQueueGetJobInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobQueueGetJobInfoCall) Return(arg0 *rivertype.JobRow, arg1 error) *MockJobQueueGetJobInfoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobQueueGetJobInfoCall) Do(f func(context.Context, int64) (*rivertype.JobRow, error)) *MockJobQueueGetJobInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobQueueGetJobInfoCall) DoAndReturn(f func(context.Context, int64) (*rivertype.JobRow, error)) *MockJobQueueGetJobInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WaitForJobCompletion mocks base method.
func (m *MockJobQueue) WaitForJobCompletion(ctx context.Context, jobID int64) (*rivertype.JobRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForJobCompletion", ctx, jobID)
	ret0, _ := ret[0].(*rivertype.JobRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitForJobCompletion indicates an expected call of WaitForJobCompletion.
func (mr *MockJobQueueMockRecorder) WaitForJobCompletion(ctx, jobID any) *MockJobQueueWaitForJobCompletionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForJobCompletion", reflect.TypeOf((*MockJobQueue)(nil).WaitForJobCompletion), ctx, jobID)
	return &MockJobQueueWaitForJobCompletionCall{Call: call}
}

// MockJobQueueWaitForJobCompletionCall wrap *gomock.Call
type MockJobQueueWaitForJobCompletionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobQueueWaitForJobCompletionCall) Return(arg0 *rivertype.JobRow, arg1 error) *MockJobQueueWaitForJobCompletionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobQueueWaitForJobCompletionCall) Do(f func(context.Context, int64) (*rivertype.JobRow, error)) *MockJobQueueWaitForJobCompletionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobQueueWaitForJobCompletionCall) DoAndReturn(f func(context.Context, int64) (*rivertype.JobRow, error)) *MockJobQueueWaitForJobCompletionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
