// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/internal/jimm/bootstrap (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -typed -destination=./mocks/store.go -package=mocks . Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dbmodel "github.com/canonical/jimm/v3/internal/dbmodel"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddControllerBootstrap mocks base method.
func (m *MockStore) AddControllerBootstrap(ctx context.Context, bootstrap *dbmodel.ControllerBootstrap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddControllerBootstrap", ctx, bootstrap)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddControllerBootstrap indicates an expected call of AddControllerBootstrap.
func (mr *MockStoreMockRecorder) AddControllerBootstrap(ctx, bootstrap any) *MockStoreAddControllerBootstrapCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddControllerBootstrap", reflect.TypeOf((*MockStore)(nil).AddControllerBootstrap), ctx, bootstrap)
	return &MockStoreAddControllerBootstrapCall{Call: call}
}

// MockStoreAddControllerBootstrapCall wrap *gomock.Call
type MockStoreAddControllerBootstrapCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreAddControllerBootstrapCall) Return(err error) *MockStoreAddControllerBootstrapCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreAddControllerBootstrapCall) Do(f func(context.Context, *dbmodel.ControllerBootstrap) error) *MockStoreAddControllerBootstrapCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreAddControllerBootstrapCall) DoAndReturn(f func(context.Context, *dbmodel.ControllerBootstrap) error) *MockStoreAddControllerBootstrapCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddJobLog mocks base method.
func (m *MockStore) AddJobLog(ctx context.Context, jobId int64, logLine string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddJobLog", ctx, jobId, logLine)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddJobLog indicates an expected call of AddJobLog.
func (mr *MockStoreMockRecorder) AddJobLog(ctx, jobId, logLine any) *MockStoreAddJobLogCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddJobLog", reflect.TypeOf((*MockStore)(nil).AddJobLog), ctx, jobId, logLine)
	return &MockStoreAddJobLogCall{Call: call}
}

// MockStoreAddJobLogCall wrap *gomock.Call
type MockStoreAddJobLogCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreAddJobLogCall) Return(err error) *MockStoreAddJobLogCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreAddJobLogCall) Do(f func(context.Context, int64, string) error) *MockStoreAddJobLogCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreAddJobLogCall) DoAndReturn(f func(context.Context, int64, string) error) *MockStoreAddJobLogCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteControllerBootstrap mocks base method.
func (m *MockStore) DeleteControllerBootstrap(ctx context.Context, bootstrap *dbmodel.ControllerBootstrap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteControllerBootstrap", ctx, bootstrap)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteControllerBootstrap indicates an expected call of DeleteControllerBootstrap.
func (mr *MockStoreMockRecorder) DeleteControllerBootstrap(ctx, bootstrap any) *MockStoreDeleteControllerBootstrapCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteControllerBootstrap", reflect.TypeOf((*MockStore)(nil).DeleteControllerBootstrap), ctx, bootstrap)
	return &MockStoreDeleteControllerBootstrapCall{Call: call}
}

// MockStoreDeleteControllerBootstrapCall wrap *gomock.Call
type MockStoreDeleteControllerBootstrapCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreDeleteControllerBootstrapCall) Return(err error) *MockStoreDeleteControllerBootstrapCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreDeleteControllerBootstrapCall) Do(f func(context.Context, *dbmodel.ControllerBootstrap) error) *MockStoreDeleteControllerBootstrapCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreDeleteControllerBootstrapCall) DoAndReturn(f func(context.Context, *dbmodel.ControllerBootstrap) error) *MockStoreDeleteControllerBootstrapCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetController mocks base method.
func (m *MockStore) GetController(ctx context.Context, controller *dbmodel.Controller) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetController", ctx, controller)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetController indicates an expected call of GetController.
func (mr *MockStoreMockRecorder) GetController(ctx, controller any) *MockStoreGetControllerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetController", reflect.TypeOf((*MockStore)(nil).GetController), ctx, controller)
	return &MockStoreGetControllerCall{Call: call}
}

// MockStoreGetControllerCall wrap *gomock.Call
type MockStoreGetControllerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreGetControllerCall) Return(err error) *MockStoreGetControllerCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreGetControllerCall) Do(f func(context.Context, *dbmodel.Controller) error) *MockStoreGetControllerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreGetControllerCall) DoAndReturn(f func(context.Context, *dbmodel.Controller) error) *MockStoreGetControllerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetControllerBootstrap mocks base method.
func (m *MockStore) GetControllerBootstrap(ctx context.Context, bootstrap *dbmodel.ControllerBootstrap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetControllerBootstrap", ctx, bootstrap)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetControllerBootstrap indicates an expected call of GetControllerBootstrap.
func (mr *MockStoreMockRecorder) GetControllerBootstrap(ctx, bootstrap any) *MockStoreGetControllerBootstrapCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetControllerBootstrap", reflect.TypeOf((*MockStore)(nil).GetControllerBootstrap), ctx, bootstrap)
	return &MockStoreGetControllerBootstrapCall{Call: call}
}

// MockStoreGetControllerBootstrapCall wrap *gomock.Call
type MockStoreGetControllerBootstrapCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreGetControllerBootstrapCall) Return(err error) *MockStoreGetControllerBootstrapCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreGetControllerBootstrapCall) Do(f func(context.Context, *dbmodel.ControllerBootstrap) error) *MockStoreGetControllerBootstrapCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreGetControllerBootstrapCall) DoAndReturn(f func(context.Context, *dbmodel.ControllerBootstrap) error) *MockStoreGetControllerBootstrapCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// QueryJobLog mocks base method.
func (m *MockStore) QueryJobLog(ctx context.Context, jobId int64, offset int) ([]string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryJobLog", ctx, jobId, offset)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QueryJobLog indicates an expected call of QueryJobLog.
func (mr *MockStoreMockRecorder) QueryJobLog(ctx, jobId, offset any) *MockStoreQueryJobLogCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryJobLog", reflect.TypeOf((*MockStore)(nil).QueryJobLog), ctx, jobId, offset)
	return &MockStoreQueryJobLogCall{Call: call}
}

// MockStoreQueryJobLogCall wrap *gomock.Call
type MockStoreQueryJobLogCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreQueryJobLogCall) Return(loggies []string, nextOffsetValue int, err error) *MockStoreQueryJobLogCall {
	c.Call = c.Call.Return(loggies, nextOffsetValue, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreQueryJobLogCall) Do(f func(context.Context, int64, int) ([]string, int, error)) *MockStoreQueryJobLogCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreQueryJobLogCall) DoAndReturn(f func(context.Context, int64, int) ([]string, int, error)) *MockStoreQueryJobLogCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateControllerBootstrap mocks base method.
func (m *MockStore) UpdateControllerBootstrap(ctx context.Context, bootstrap *dbmodel.ControllerBootstrap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateControllerBootstrap", ctx, bootstrap)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateControllerBootstrap indicates an expected call of UpdateControllerBootstrap.
func (mr *MockStoreMockRecorder) UpdateControllerBootstrap(ctx, bootstrap any) *MockStoreUpdateControllerBootstrapCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateControllerBootstrap", reflect.TypeOf((*MockStore)(nil).UpdateControllerBootstrap), ctx, bootstrap)
	return &MockStoreUpdateControllerBootstrapCall{Call: call}
}

// MockStoreUpdateControllerBootstrapCall wrap *gomock.Call
type MockStoreUpdateControllerBootstrapCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreUpdateControllerBootstrapCall) Return(err error) *MockStoreUpdateControllerBootstrapCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreUpdateControllerBootstrapCall) Do(f func(context.Context, *dbmodel.ControllerBootstrap) error) *MockStoreUpdateControllerBootstrapCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreUpdateControllerBootstrapCall) DoAndReturn(f func(context.Context, *dbmodel.ControllerBootstrap) error) *MockStoreUpdateControllerBootstrapCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
