// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/internal/jimm/bootstrap (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -typed -destination=./mocks/store.go -package=mocks . Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	dbmodel "github.com/canonical/jimm/v3/internal/dbmodel"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddJobLog mocks base method.
func (m *MockStore) AddJobLog(ctx context.Context, jobId uuid.UUID, logLine string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddJobLog", ctx, jobId, logLine)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddJobLog indicates an expected call of AddJobLog.
func (mr *MockStoreMockRecorder) AddJobLog(ctx, jobId, logLine any) *MockStoreAddJobLogCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddJobLog", reflect.TypeOf((*MockStore)(nil).AddJobLog), ctx, jobId, logLine)
	return &MockStoreAddJobLogCall{Call: call}
}

// MockStoreAddJobLogCall wrap *gomock.Call
type MockStoreAddJobLogCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreAddJobLogCall) Return(err error) *MockStoreAddJobLogCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreAddJobLogCall) Do(f func(context.Context, uuid.UUID, string) error) *MockStoreAddJobLogCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreAddJobLogCall) DoAndReturn(f func(context.Context, uuid.UUID, string) error) *MockStoreAddJobLogCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetController mocks base method.
func (m *MockStore) GetController(ctx context.Context, controller *dbmodel.Controller) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetController", ctx, controller)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetController indicates an expected call of GetController.
func (mr *MockStoreMockRecorder) GetController(ctx, controller any) *MockStoreGetControllerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetController", reflect.TypeOf((*MockStore)(nil).GetController), ctx, controller)
	return &MockStoreGetControllerCall{Call: call}
}

// MockStoreGetControllerCall wrap *gomock.Call
type MockStoreGetControllerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreGetControllerCall) Return(err error) *MockStoreGetControllerCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreGetControllerCall) Do(f func(context.Context, *dbmodel.Controller) error) *MockStoreGetControllerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreGetControllerCall) DoAndReturn(f func(context.Context, *dbmodel.Controller) error) *MockStoreGetControllerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LockBootstrap mocks base method.
func (m *MockStore) LockBootstrap(ctx context.Context, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockBootstrap", ctx, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockBootstrap indicates an expected call of LockBootstrap.
func (mr *MockStoreMockRecorder) LockBootstrap(ctx, ttl any) *MockStoreLockBootstrapCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockBootstrap", reflect.TypeOf((*MockStore)(nil).LockBootstrap), ctx, ttl)
	return &MockStoreLockBootstrapCall{Call: call}
}

// MockStoreLockBootstrapCall wrap *gomock.Call
type MockStoreLockBootstrapCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreLockBootstrapCall) Return(arg0 error) *MockStoreLockBootstrapCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreLockBootstrapCall) Do(f func(context.Context, time.Duration) error) *MockStoreLockBootstrapCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreLockBootstrapCall) DoAndReturn(f func(context.Context, time.Duration) error) *MockStoreLockBootstrapCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// QueryJobLog mocks base method.
func (m *MockStore) QueryJobLog(ctx context.Context, jobId uuid.UUID, offset int) ([]string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryJobLog", ctx, jobId, offset)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QueryJobLog indicates an expected call of QueryJobLog.
func (mr *MockStoreMockRecorder) QueryJobLog(ctx, jobId, offset any) *MockStoreQueryJobLogCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryJobLog", reflect.TypeOf((*MockStore)(nil).QueryJobLog), ctx, jobId, offset)
	return &MockStoreQueryJobLogCall{Call: call}
}

// MockStoreQueryJobLogCall wrap *gomock.Call
type MockStoreQueryJobLogCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreQueryJobLogCall) Return(loggies []string, nextOffsetValue int, err error) *MockStoreQueryJobLogCall {
	c.Call = c.Call.Return(loggies, nextOffsetValue, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreQueryJobLogCall) Do(f func(context.Context, uuid.UUID, int) ([]string, int, error)) *MockStoreQueryJobLogCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreQueryJobLogCall) DoAndReturn(f func(context.Context, uuid.UUID, int) ([]string, int, error)) *MockStoreQueryJobLogCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UnlockBootstrap mocks base method.
func (m *MockStore) UnlockBootstrap(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockBootstrap", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockBootstrap indicates an expected call of UnlockBootstrap.
func (mr *MockStoreMockRecorder) UnlockBootstrap(ctx any) *MockStoreUnlockBootstrapCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockBootstrap", reflect.TypeOf((*MockStore)(nil).UnlockBootstrap), ctx)
	return &MockStoreUnlockBootstrapCall{Call: call}
}

// MockStoreUnlockBootstrapCall wrap *gomock.Call
type MockStoreUnlockBootstrapCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreUnlockBootstrapCall) Return(arg0 error) *MockStoreUnlockBootstrapCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreUnlockBootstrapCall) Do(f func(context.Context) error) *MockStoreUnlockBootstrapCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreUnlockBootstrapCall) DoAndReturn(f func(context.Context) error) *MockStoreUnlockBootstrapCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
