// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/internal/jimm/bootstrap (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/store.go -package=mocks . Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	dbmodel "github.com/canonical/jimm/v3/internal/dbmodel"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddBootstrapLog mocks base method.
func (m *MockStore) AddBootstrapLog(ctx context.Context, jobId uuid.UUID, logLine string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBootstrapLog", ctx, jobId, logLine)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBootstrapLog indicates an expected call of AddBootstrapLog.
func (mr *MockStoreMockRecorder) AddBootstrapLog(ctx, jobId, logLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBootstrapLog", reflect.TypeOf((*MockStore)(nil).AddBootstrapLog), ctx, jobId, logLine)
}

// GetController mocks base method.
func (m *MockStore) GetController(ctx context.Context, controller *dbmodel.Controller) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetController", ctx, controller)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetController indicates an expected call of GetController.
func (mr *MockStoreMockRecorder) GetController(ctx, controller any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetController", reflect.TypeOf((*MockStore)(nil).GetController), ctx, controller)
}

// LockBootstrap mocks base method.
func (m *MockStore) LockBootstrap(ctx context.Context, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockBootstrap", ctx, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockBootstrap indicates an expected call of LockBootstrap.
func (mr *MockStoreMockRecorder) LockBootstrap(ctx, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockBootstrap", reflect.TypeOf((*MockStore)(nil).LockBootstrap), ctx, ttl)
}

// QueryBootstrapLog mocks base method.
func (m *MockStore) QueryBootstrapLog(ctx context.Context, jobId uuid.UUID, offset int) ([]string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryBootstrapLog", ctx, jobId, offset)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QueryBootstrapLog indicates an expected call of QueryBootstrapLog.
func (mr *MockStoreMockRecorder) QueryBootstrapLog(ctx, jobId, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryBootstrapLog", reflect.TypeOf((*MockStore)(nil).QueryBootstrapLog), ctx, jobId, offset)
}

// UnlockBootstrap mocks base method.
func (m *MockStore) UnlockBootstrap(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockBootstrap", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockBootstrap indicates an expected call of UnlockBootstrap.
func (mr *MockStoreMockRecorder) UnlockBootstrap(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockBootstrap", reflect.TypeOf((*MockStore)(nil).UnlockBootstrap), ctx)
}
