name: Cache on default branch
on:
  push:
    branches:
      - v3
      - "feature*"

jobs:
  go_cache:
    name: Install And Cache Go Dependencies and Build Artifacts
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Add volume files
        run: |
          touch ./local/vault/approle.json
          touch ./local/vault/roleid.txt
          touch ./local/vault/vault.env

      - name: Build
        run: go build ./...
