name: Cache on default branch
on:
  push:
    branches:
      - v3
      - "feature*"

jobs:
  go_cache:
    name: Cache Go Dependencies and Build/Lint Artifacts
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: go build ./...

      - name: Run Golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout 30m --verbose
          version: v1.60
