name: Charm Test
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - charms/**

jobs:
  charm-build:
    uses: ./.github/workflows/charm-build.yaml

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        charm-type: ["jimm","jimm-k8s"]
    defaults:
      run:
        working-directory: ./charms/${{ matrix.charm-type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        charm-type: ["jimm","jimm-k8s"]
    defaults:
      run:
        working-directory: ./charms/${{ matrix.charm-type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: tox -e unit
  integration-tests:
    name: Integration tests
    needs:
      - charm-build
    runs-on: ubuntu-latest
    env:
      charm-type: "jimm-k8s"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 2.9/stable
          provider: microk8s
          microk8s-addons: "ingress storage dns rbac registry"
          channel: 1.27/stable
      # Download the charm from the build to speed up integration tests.
      - uses: actions/download-artifact@master
        with:
          name: jimm-k8s-charm
          path: ./charms/${{ env.charm-type }}
      - name: Create OCI Image
        run: make push-microk8s
      - name: Install tox
        run: python -m pip install tox
      - name: Integration tests
        run: tox -e integration -- --localCharm
        working-directory: ./charms/${{ env.charm-type }}
