name: Charm Test
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - charms/**

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        charm-type: ["jimm","jimm-k8s"]
    defaults:
      run:
        working-directory: ./charms/${{ matrix.charm-type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        charm-type: ["jimm","jimm-k8s"]
    defaults:
      run:
        working-directory: ./charms/${{ matrix.charm-type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: tox -e unit
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        charm-type: ["jimm-k8s"]
    defaults:
      run:
        working-directory: ./charms/${{ matrix.charm-type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 2.9/stable
          provider: microk8s
          microk8s-addons: "ingress storage dns rbac registry"
          channel: 1.27/stable
      - name: Install dependencies
        run: python -m pip install tox
      - name: Integration tests
        run: tox -e integration
