name: CI
on:
  pull_request:
    paths:
      - '.github/**'  # Run this workflow when the only files changed were any in .github
  workflow_call:
  workflow_dispatch:

jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
