name: E2E Test

on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-test:
    name: E2E Tests (${{ matrix.name }})
    timeout-minutes: 60
    runs-on: [self-hosted-linux-amd64-jammy-large]
    strategy:
      matrix:
        include:
          - name: "Juju 3"
            versions: '["3/stable", "3/stable"]'
          - name: "Juju 4"
            versions: '["4.0/stable", "4.0/stable"]'
          - name: "Mix"
            versions: '["3/stable", "4.0/stable"]'
    steps:
      - name: Checkout JIMM repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: false

      - name: Set up JIMM environment
        uses: ./.github/actions/setup-jimm-env
        with:
          cli-channel: ${{ fromJSON(matrix.versions)[0] }}
          controller-channels: ${{ matrix.versions }}

      - name: Run E2E tests
        run: go test -v ./testing/... -timeout 30m
        env:
          RUN_E2E_TESTS: "1"
          JIMM_MICROK8S_TEST_CLOUD_NAME: "microk8s-cp"
          JIMM_BACKING_CONTROLLER_CONFIG: ${{ github.workspace }}/controllers.yaml
