name: E2E Test

on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-test:
    name: E2E Tests with External Controller
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout JIMM repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Install dependencies
        run: sudo apt-get update -y && sudo apt-get install -y gcc git-core gnupg build-essential

      - name: Install Juju
        run: |
          sudo snap install juju --channel=3.6/stable
          mkdir -p ~/.local/share/juju

      - name: Initialise LXD
        run: |
          sudo lxd waitready && \
          sudo lxd init --auto && \
          sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket && \
          lxc network set lxdbr0 ipv6.address none && \
          sudo usermod -a -G lxd $USER && \
          sudo iptables -F FORWARD && \
          sudo iptables -P FORWARD ACCEPT
      
      - name: Generate certs
        working-directory: local/traefik/certs
        run: ./certs.sh
      
      - name: Start test environment
        run: make test-env

      - name: Bootstrap controller with JWKS endpoint
        run: |
          JWKS_DNS=jwks.localhost CONTROLLER_NAME=test-e2e ./local/jimm/setup-controller.sh

      - name: Generate controller config
        run: CONTROLLER=test-e2e make generate-test-env

      - name: Run E2E tests
        run: go test -v ./testing/... -timeout 30m
        env:
          RUN_E2E_TESTS: "1"
          JIMM_BACKING_CONTROLLER_CONFIG: ${{ github.workspace }}/controllers.yaml
