name: golangci-lint
on:
  pull_request:

permissions:
  contents: read
  checks: write # Optional: allow write access to checks to allow the action to annotate code in the PR.

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout 50m --verbose
          version: v1.60
