name: Publish Docs

# This workflow builds the jaas plugin and generates a markdown 
# formatted document before converting the doc to rst and makes
# a PR to the jaas-documentation repo to update the docs.

on:
  workflow_dispatch:
  push:
    tags:
      - 'v3*'

jobs:
  publish-jaas-plugin-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - run: git fetch --tags --force origin # https://github.com/actions/checkout/issues/882 & https://github.com/actions/checkout/issues/290 

    - name: Build jaas
      run: go build ./cmd/jaas/

      # Default doc name is documentation.md which can't be changed via flags.
    - name: Generate docs
      run: ./jaas documentation --no-index=true --out .

    - name: Convert doc to reStructuredText
      uses: docker://pandoc/core:3.5
      with:
        args: "documentation.md -o documentation.rst --wrap=none"

      # We do this because the original doc doesn't have a top level heading.: 
    - name: Create final doc with title
      run: |
        echo "\`\`jaas\`\` Reference" > jaas-reference.rst
        echo "##################" >> jaas-reference.rst
        echo "" >> jaas-reference.rst
        cat documentation.rst >> jaas-reference.rst
    
    - name: Checkout docs
      uses: actions/checkout@v4
      with:
        repository: 'canonical/jaas-documentation'
        ref: 'v3'
        path: ./jaas-documentation
  
    - name: Update Docs
      working-directory: ./jaas-documentation
      run: cp ../jaas-reference.rst ./reference/jaas.rst

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.JIMM_DOCS_TOKEN }}
        path: ./jaas-documentation
        branch: update-jaas-${{ github.run_number }}
        title: Update jaas reference doc
        body: |
          This PR contains a generated documentation reference
          for the jaas CLI tool for release ${{ github.event.ref }}.
        commit-message: Updated jaas reference for release ${{ github.event.ref }}
