name: Release binaries

on:
  workflow_call:

# GitHub considers creating releases and uploading assets as writing contents.
permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-22.04
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Free additional space
        shell: bash
        run: |
          # Remove tools/caches that aren't required for this run.
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"/CodeQL
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"/Ruby
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"/Java_Temurin-Hotspot_jdk
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0

      - name: Set up Go
        uses:  actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: false
  
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
        env:
          # GitHub sets the GITHUB_TOKEN secret automatically.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
