name: Release Snaps

on:
  workflow_dispatch:
  push:
    tags:
      - 'v3*'

jobs:
  build-and-release-jimmctl:
    uses: ./.github/workflows/snap-release.yaml
    with:
      folder: jimmctl
      release-channel: 3/edge
    secrets: inherit

  build-and-release-jaas-plugin:
    uses: ./.github/workflows/snap-release.yaml
    with:
      folder: jaas
      release-channel: 3/edge
    secrets: inherit

  build-and-release-jimm-server:
    uses: ./.github/workflows/snap-release.yaml
    with:
      jobs: build # Only build, this snap isn't released to snapcraft
      folder: jimm
      release-channel: 3/edge # Not used for this snap
    secrets: inherit

