name: Security Scan Weekly

on:
  schedule:
    - cron: "0 0 * * 1" # Runs every Monday at 00:00 UTC.
  workflow_dispatch:

jobs:
  repo-security-scan:
    runs-on: [ubuntu-latest]
    name: Repo Security Scan
    strategy:
      matrix:
        branch: [v3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Security scan
        uses: canonical/comsys-build-tools/.github/actions/security-scan-upload@main
        with: 
          upload-github-security: "true"
          upload-sarif-artifact: "true"

  container-security-scan:
    runs-on: [ubuntu-latest]
    name: Container Security Scan
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'ghcr.io/canonical/jimm:latest'
          format: 'sarif'
          output: 'container-trivy-results.sarif'

      - name: Upload container Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'container-trivy-results.sarif'
