name: TIOBE scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # Runs every Monday at 00:00 UTC.

jobs:
  build:
    runs-on: [self-hosted, linux, amd64, tiobe, jammy]
    steps:
    - name: Checkout the project
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: "go.mod"

    - name: Install dependencies
      run: |
        sudo apt-get update -y && sudo apt-get install -y gcc git-core gnupg build-essential
        go install honnef.co/go/tools/cmd/staticcheck@v0.6.1
        go install github.com/t-yuki/gocover-cobertura@latest

    - name: Install Docker
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          ca-certificates \
          curl \
          gnupg \
          lsb-release
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update -y
        sudo snap install docker # installing via apt doesn't work, because you can't start systemctl services.
        sudo apt-get install -y docker-compose-plugin
    
    - name: Start test environment
      run: docker compose up -d --wait
    
    - name: Test and generate coverage report
      run: |
        TEST_LOGGING_CONFIG=ERROR go test -mod readonly ./... -timeout 1h -coverprofile=coverage.out
        mkdir -p .coverage
        gocover-cobertura < coverage.out > .coverage/coverage.xml

    - name: Run TICS analysis with github-action
      uses: tiobe/tics-github-action@v3
      with:
        mode: qserver
        project: jimm
        branchdir: .
        viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=GoProjects
        ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
        installTics: true

    - name: echo URL to TIOBE dashboard
      run: |
        echo 'Go here to see the results: https://canonical.tiobe.com/tiobeweb/TICS/Explorer.html#axes=ProjectGroup(PrivateRepos),Project(jimm)'
