storage:
    type: postgres
    connection-string: postgresql://jimm:jimm@db:5432/jimm?sslmode=disable
logging-config: "DEBUG"
auth-username: admin
auth-password: password
listen-address: 0.0.0.0:8081
location: 'http://0.0.0.0:8081'
private-addr: "0.0.0.0"
private-key: 8PjzjakvIlh3BVFKe8axinRDutF6EDIfjtuf4+JaNow=
public-key: CIdWcEUN+0OZnKW9KwruRQnQDY/qqzVdD30CijwiWCk=
access-log: access.log
max-mgo-sessions: 300
request-timeout: 2s
admin-agent-public-key: iKp24EL2Aj9MQfRkpwzp7rz7Zf3QZsEzWGpoWT3OK2w=
identity-providers:
- type: static
  name: static
  description: Default identity provider
  domain: candid.localhost
  users:
    jimm:
      name: JIMM User
      email: jimm.user@example.com
      password: jimm
      groups:
       - group1
       - group2
    joe:
      name: Joe user (non superuser)
      email: joe.user@example.com
      password: joe
      groups:
       - group1
       - group2
  hidden: false
  require-mfa: false