storage:
    type: memory
logging-config: "DEBUG"
listen-address: 0.0.0.0:8081
auth-username: admin
auth-password: password
location: 'http://0.0.0.0:8081'
private-key: 8PjzjakvIlh3BVFKe8axinRDutF6EDIfjtuf4+JaNow=
public-key: CIdWcEUN+0OZnKW9KwruRQnQDY/qqzVdD30CijwiWCk=
access-log: access.log
max-mgo-sessions: 300
request-timeout: 2s
private-addr: localhost
admin-agent-public-key: iKp24EL2Aj9MQfRkpwzp7rz7Zf3QZsEzWGpoWT3OK2w=
identity-providers:
- type: static
  name: static
  description: Default identity provider
  users:
    jimm:
      name: JIMM User
      email: jimm.user@example.com
      password: jimm
      groups:
       - group1
       - group2
  hidden: false
  require-mfa: false